### ISSUE TITLE
Temperature chart

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#1054]
SENEC-Collector already gets and stores the **case temperature** (since [v0.5.0](https://github.com/solectrus/senec-collector/releases/tag/v0.5.0)). 

A chart should be added to displays this data.

**Comment by Zeppelin-PV** [comment]
hallo Georg
nochmals zu den Charts im allgemeinen.
Die Anzeigebox ist ja nun mittlerweile etwas vom Messwertpunkt weggerückt. Gut so.
Der Messwertpunkt ist in der gleichen Farbe wie die Grafik. Kann man den Messpunkten nicht zumindest einen schwarzen Rand verpassen, oder womöglich in einer Konträrfarbe darstellen ?
LG Ernst

**Comment by ledermann** [comment]
Temperature charts are included in the just released version 0.10.0
