### ISSUE TITLE
Charts: Missing label of first day/month/year

### ISSUE THREAD

**Issue by bennysweb** [solectrus/solectrus#1611]
In the overview for "Woche", "Monat", "Jahr" and "Gesamt" is the first date missing. This is no bug especially in the actual version, I've observed this in the older versions too. Can this be improved?
Best regards,
Benny

By the way: GREAT WORK, many thanks for this!
![image](https://user-images.githubusercontent.com/77127461/211213259-8ce23f95-5b2b-4d4a-a81b-22af6a1a5d9c.jpeg)
![image](https://user-images.githubusercontent.com/77127461/211213266-d10e2472-e6fd-4f51-b0eb-4cf3cc6e30ae.jpeg)
![image](https://user-images.githubusercontent.com/77127461/211213272-ba17f7a5-fb4c-44b4-89da-506afcdb1caa.jpeg)
![image](https://user-images.githubusercontent.com/77127461/211213930-8249af81-1ff4-4dfb-9652-b31be32afa1b.jpeg)

**Comment by ledermann** [comment]
@bennysweb Thank you for pointing this out. I will fix this soon.

**Comment by ledermann** [comment]
Fixed in development branch (see online at https://solectrus.ledermann.dev).
Will be published in next regular release.
