### ISSUE TITLE
Autarky values  missing in diagram

### ISSUE THREAD

**Issue by iot-sle** [solectrus/solectrus#1726]
For some reason the autarky diagram isn't filled in all the time. I attached 2 screenshots. It seems that the values are available, because the sum is shown. If you need more details or access to the dbs, pls send a personal mail.

|                         |                        |
| ------------- | ------------- |
|![Screenshot_20230213-134510_Opera](https://user-images.githubusercontent.com/74416643/218515857-d9ab04b2-3692-43dd-bd5a-c5605d2d1159.jpg)|![Screenshot_20230213-134414_Opera](https://user-images.githubusercontent.com/74416643/218515880-d1bd9389-3d62-4f6b-af3e-b212f3baed22.jpg)|

**Comment by ledermann** [comment]
There are two things I suggest to check:

1) Is your ENV var `INSTALLATION_DATE`correct? It should point to the installation date of your SENEC (= date with first data)

2) Maybe there is a caching issue. You can reset your Redis cache with this command:

    `docker exec -it [solectrus-redis-container-name] redis-cli FLUSHALL`
    e.g. `docker exec -it solectrus-redis-1 redis-cli FLUSHALL`

   This may happen if you have imported data (using [senec-importer](https://github.com/solectrus/senec-importer)) **after** the app was already used and has filled the cache.

If neither of these helps: What about other charts? Are they also empty? What about `house_power`chart in August 2022?

**Comment by iot-sle** [comment]
no success by executing the flushall. All other charts are fine.

**Comment by ledermann** [comment]
Strange. Are there any errors in the browser console or in the container logs?

Is your SOLECTRUS installation accessible to the public? May I have a look at it? Or can you give me private access (via e-mail)?

**Comment by iot-sle** [comment]
Did you receive my email about accessing my instalation? I just updated to 0.8.0 and it's still the same behavior according this chart. I like the live-status display.

**Comment by ledermann** [comment]
No email so far. Please send to info@solectrus.de

**Comment by ledermann** [comment]
Thanks to @iot-sle, this error was identified and confirmed. It occurs for the periods that were filled with SENEC's CSV data via the [senec-importer](https://github.com/solectrus/senec-importer). These data sets do not contain any measurements for the wallbox, meaning that these values are stored as `NULL`, which breaks the autarky calculation by InfluxDB.

A fix has been implemented - NULL values are now converted to zero (`0.0`). The fix will be included in the next update (expected to be v0.8.1).
