### ISSUE TITLE
[Feature Request] Display Current Battery Precentage

### ISSUE THREAD

**Issue by Twooearly** [solectrus/solectrus#1734]
As I saw, the Current Battery Percentage is shown on the new Layout there:
![image](https://user-images.githubusercontent.com/82608982/219003159-cbacf4ff-5187-41d5-8fe6-caf8d75a36b7.png)

Also this Value ist monitored in the InfluxDB and can be accessed at [https://solectrus-domain.com/bat_fuel_charge/](https://solectrus.ledermann.dev/bat_fuel_charge/)
Could you implement it, that the chart at this URL gets a proper Color and can be accessed when clicking on the Current Battery Percentage.

I hope this isn't too hard and it would be a huge improvement to daily use for me.
Hope you can make use of this. Have a great Day!

**Comment by ledermann** [comment]
Well observed :) Yes, there is a hidden battery chart, which works fine for line charts of "NOW" and "DAY" (currently not colorized). Example here:
https://solectrus.ledermann.dev/bat_fuel_charge/2023-02-16

However, it does not make sense for bar charts (Week, Month, Year, All). This is the reason I have not yet added a link to this chart. I still need to figure out the best way to solve this.

**Comment by ledermann** [comment]
Just released as v0.10.0
