### ISSUE TITLE
Display of forecast

### ISSUE THREAD

**Issue by bennysweb** [solectrus/solectrus#1751]
Is it possible to improve the display of the forecast? My suggestion would be: "Genau wie erwartet" or something like that. 
![image](https://user-images.githubusercontent.com/77127461/220214547-92c14d8e-b833-4ee7-afeb-a5079a56ba65.png)

**Comment by ledermann** [comment]
Good catch! I just fixed it, example here:
https://solectrus.ledermann.dev/inverter_power/2022-12-28

Will be included in the next release.

**Comment by ledermann** [comment]
v0.9.0 including this fix was released today
