### ISSUE TITLE
Forecast: No further expectation after sunset

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#1766]
If after sunset the expected power has not been reached, the display shall change from

    "Expected [x] kWh"

to 

    "[y] % less than expected"

**Comment by Zeppelin-PV** [comment]
hallo Georg
den Tagesabschluss nach Sonnenuntergang auszuwerten ist gut
so lässt sich erkennen ob die PV mehr oder weniger geleistet hat.
Die Auswertung in Prozent auch ok, aber in dem Moment fehlt der Bezug zur Größe
sprich die kW's die erwartet wurden,
das gilt auch für die Vortage
der erwartete Wert sollte wenn möglich zusätzlich dargestellt werden
z.B.   17 % weniger als erwartet (xxx kW)

LG Ernst
