### ISSUE TITLE
Generating values: calculation bug?

### ISSUE THREAD

**Issue by bennysweb** [solectrus/solectrus#1770]
In addition to #1769: 
The calculation for the generating values is not correct. In January my system generates 209kWh, in February 424kWh. The year view means my system has generated 621kWh. In reality the system has generated 633kWh. When I compare the values with those from the senec website, the monthly data are shown correct. Just the value from the year tab is not correct. 
When I check the solectrus values from your website for January, February and 2023 I can find the same wrong values. 

See also my screenshots in #1769

**Comment by ledermann** [comment]
v0.9.0 including this fix was released today
