### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by Zeppelin-PV** [solectrus/solectrus#1873]
zur Zeit häufen sich Verbesserungsvorschläge und Implemetierugswünsche bei Solectrus.
Ich sehe daraus ein großes Bedürfniss einer Bediener Schnittstelle.
Viele der zuletzt eingegangenen Anfragen liesen sich damit erschlagen.
- individuelles Farbschema
- Import historischer Daten
- Push Meldung bei Temperaturproblemen
- Parameter der PV-Anlage
- Geo-Daten für Forecast
- Anzeige kW-->Watt
- Euro in Cent (da oft 3-4 stellig nach Komma)
- sonst noch was ???

Vielleicht gibt es noch von anderer Seite interessante Punkte für ein UI.

**Comment by ledermann** [comment]
Verbesserungsvorschläge sollten weiterhin als separate Issues erfasst werden, da sie unabhängig voneinander diskutiert und implementiert werden können. 

Alles nochmals in einem eigenen Issue zusammenzufassen, ist meiner Ansicht nach nicht sinnvoll. Wenn überhaupt, dann ist so etwas in den [Discussions](https://github.com/orgs/solectrus/discussions) besser aufgehoben.
