### ISSUE TITLE
Diagramme mit Farbverlauf

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#1881]
von @Zeppelin-PV in #1859

> die Grafikfelder erscheinen, je nach Einfärbung, globik, schwer.
> Wäre es machbar hier von den Werten (dunkle Linie) hin zur Null-Linie ein Ausbleichen der Farbe zu gestalten ?
> Somit käme die Grafik viel lockerer daher.
> Bei den Top Ten Balken ist dies ein wenig ersichtlich.

**Comment by StevieC121176** [comment]
Vielleicht könnte man es so in der Art machen, Bild 1 ist mit Farbverlauf hell und dunkle Umrandung , Bild 2 helle Farben und dunkle Umrandung.

![IMG_0932](https://github.com/solectrus/solectrus/assets/113791299/ee2dad50-644f-4690-9be5-a9e9f428a37e)



![IMG_0933](https://github.com/solectrus/solectrus/assets/113791299/0be46152-366e-4728-bfa3-d30a02e039c5)

**Comment by ledermann** [comment]
Ja, das sieht gut aus. Ich verwende für die Diagramme [Chart.js](https://www.chartjs.org/) und bin an die davon angebotenen Möglichkeiten gebunden. Aber ein Farbverlauf erscheint machbar: http://jsfiddle.net/4vobe59a/

**Comment by StevieC121176** [comment]
Das Beispiel aus dem Link schaut gut aus.Farbverlauf und die stärker hervorgehobene Kante ist dort auch zu sehen

**Comment by ledermann** [comment]
Das habe ich jetzt mal umgesetzt. Sämtliche Diagramme erscheinen nun mit einem Farbverlauf.

Dies wird im nächsten Update enthalten sein, in der [Live-Demo](https://solectrus.ledermann.dev) ist es ab sofort zu sehen.

**Comment by StevieC121176** [comment]
Vielen Dank, gefällt mir sehr gut.

**Comment by StevieC121176** [comment]
Eine Kleinigkeit zur Optik: Bei der Anzeige Verwendung und Herkunft sind die Ecken leicht abgerundet dargestellt. Vielleicht wäre das bei den Balkendiagrammen auch möglich und würde diese etwas "weicher" aussehen lassen. Als Beispiel hier die Small rounded Balken bei Charts.js. https://www.chartjs.org/docs/latest/samples/bar/border-radius.html
