### ISSUE TITLE
InfluxDB: unauthorized access

### ISSUE THREAD

**Issue by TheBrain8788** [solectrus/solectrus#1885]
Error while pushing record #xx to influx DB: unauthorized acces 

Nach Update auf 0.10.0

**Comment by TheBrain8788** [comment]
root@pi64:/home/pi/solectrus# docker ps -q | xargs -L 1 -P `docker ps | wc -l` docker logs --since 30s -f
Error while pushing record #67 to InfluxDB: unauthorized access
The record has been queued. Will retry to push 133 records later.

Got record #134 from SENEC at 192.168.2.118: PEAK-SHAVING: WARTEN, Inverter 5701 W, House 551 W, 2023-04-03 09:55:13 +0000
Error while pushing record #34 to InfluxDB: unauthorized access
The record has been queued. Will retry to push 134 records later.

Got record #135 from SENEC at 192.168.2.118: PEAK-SHAVING: WARTEN, Inverter 7852 W, House 782 W, 2023-04-03 09:55:18 +0000
Error while pushing record #68 to InfluxDB: unauthorized access
The record has been queued. Will retry to push 135 records later.

Got record #136 from SENEC at 192.168.2.118: PV + ENTLADEN, Inverter 8027 W, House 1936 W, 2023-04-03 09:55:23 +0000
Error while pushing record #9 to InfluxDB: unauthorized access
The record has been queued. Will retry to push 136 records later.

Got record #137 from SENEC at 192.168.2.118: PV + ENTLADEN, Inverter 6451 W, House 963 W, 2023-04-03 09:55:28 +0000
Error while pushing record #69 to InfluxDB: unauthorized access
The record has been queued. Will retry to push 137 records later.

Got record #138 from SENEC at 192.168.2.118: PEAK-SHAVING: WARTEN, Inverter 7638 W, House 766 W, 2023-04-03 09:55:33 +0000
Error while pushing record #35 to InfluxDB: unauthorized access
The record has been queued. Will retry to push 138 records later.

Got record #139 from SENEC at 192.168.2.118: PV + ENTLADEN, Inverter 8375 W, House 871 W, 2023-04-03 09:55:38 +0000
ts=2023-04-03T09:55:15.214960Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
ts=2023-04-03T09:55:20.223041Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
ts=2023-04-03T09:55:25.231475Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
ts=2023-04-03T09:55:30.240495Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
ts=2023-04-03T09:55:35.252211Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
ts=2023-04-03T09:55:40.262420Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
ts=2023-04-03T09:55:45.268814Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
Error while pushing record #70 to InfluxDB: unauthorized access
The record has been queued. Will retry to push 139 records later.

Got record #140 from SENEC at 192.168.2.118: PV + ENTLADEN, Inverter 8458 W, House 802 W, 2023-04-03 09:55:43 +0000
ts=2023-04-03T09:55:50.278746Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
Error while pushing record #18 to InfluxDB: unauthorized access
The record has been queued. Will retry to push 140 records later.

Got record #141 from SENEC at 192.168.2.118: PV + ENTLADEN, Inverter 8644 W, House 851 W, 2023-04-03 09:55:49 +0000
I, [2023-04-03T09:55:53.997985 #10]  INFO -- : [192.168.2.101] method=GET path=/ format=html controller=HomeController action=index status=302 duration=4.27 view=0.00 location=http://192.168.2.20:3000/inverter_power/now user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
I, [2023-04-03T09:55:54.185482 #10]  INFO -- : [192.168.2.101] method=GET path=/inverter_power/now format=html controller=HomeController action=index status=200 duration=104.32 view=101.85 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
ts=2023-04-03T09:55:54.511044Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
I, [2023-04-03T09:55:54.513424 #10]  INFO -- : [192.168.2.101] method=GET path=/stats/inverter_power/now format=html controller=StatsController action=index status=500 duration=7.85 view=0.00 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
F, [2023-04-03T09:55:54.515963 #10] FATAL -- : [192.168.2.101]
[192.168.2.101] ActionView::Template::Error (unauthorized access):
[192.168.2.101]     1: turbo-stream action="update" target="nav"
[192.168.2.101]     2:   template
[192.168.2.101]     3:     = render Timeframe::Component.new(timeframe:)
[192.168.2.101]     4:     = render Status::Component.new(time: calculator.time, current_state: calculator.current_state) if timeframe.now?
[192.168.2.101]     5:
[192.168.2.101]     6: turbo-stream action="morph" target="stats" children-only= true
[192.168.2.101]     7:   template
[192.168.2.101]
[192.168.2.101] app/services/flux/reader.rb:53:in `query_without_cache'
[192.168.2.101] app/services/flux/reader.rb:48:in `query'
[192.168.2.101] app/services/power_sum.rb:15:in `last'
[192.168.2.101] app/services/power_sum.rb:6:in `call'
[192.168.2.101] app/services/calculator/now.rb:19:in `initialize'
[192.168.2.101] app/controllers/stats_controller.rb:12:in `new'
[192.168.2.101] app/controllers/stats_controller.rb:12:in `calculator'
[192.168.2.101] app/controllers/stats_controller.rb:11:in `calculator'
[192.168.2.101] app/views/stats/index.turbo_stream.slim:4
[192.168.2.101] app/controllers/stats_controller.rb:5:in `index'
[192.168.2.101] app/controllers/concerns/auto_locale.rb:14:in `switch_locale'
I, [2023-04-03T09:55:54.522615 #10]  INFO -- : [192.168.2.101] method=GET path=/500 format=html controller=ErrorsController action=show status=500 duration=2.47 view=1.73 user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
** [Honeybadger] Unable to send error report: API key is missing. id=3ede6275-b738-4365-b562-fb59ab7b9800 level=3 pid=10Error while pushing record #71 to InfluxDB: unauthorized access
ts=2023-04-03T09:55:55.285128Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
The record has been queued. Will retry to push 141 records later.

Got record #142 from SENEC at 192.168.2.118: PEAK-SHAVING: WARTEN, Inverter 8859 W, House 827 W, 2023-04-03 09:55:54 +0000
ts=2023-04-03T09:56:00.290321Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
Error while pushing record #36 to InfluxDB: unauthorized access
The record has been queued. Will retry to push 142 records later.

Got record #143 from SENEC at 192.168.2.118: PEAK-SHAVING: WARTEN, Inverter 8921 W, House 796 W, 2023-04-03 09:55:59 +0000

ets=2023-04-03T09:56:05.300601Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
Error while pushing record #72 to InfluxDB: unauthorized access
The record has been queued. Will retry to push 143 records later.
x
Got record #144 from SENEC at 192.168.2.118: PEAK-SHAVING: WARTEN, Inverter 9100 W, House 810 W, 2023-04-03 09:56:04 +0000
ts=2023-04-03T09:56:10.306772Z lvl=info msg=Unauthorized log_id=0gycs~Gl000 error="authorization not found"
Error while pushing record #3 to InfluxDB: unauthorized access
The record has been queued. Will retry to push 144 records later.

Got record #145 from SENEC at 192.168.2.118: PEAK-SHAVING: WARTEN, Inverter 9330 W, House 930 W, 2023-04-03 09:56:09 +0000
^C

**Comment by TheBrain8788** [comment]
root@pi64:/home/pi/solectrus# docker ps
CONTAINER ID   IMAGE                                         COMMAND                  CREATED             STATUS                    PORTS                                       NAMES
960dab200063   ghcr.io/solectrus/solectrus:latest            "docker/startup.sh"      About an hour ago   Up 15 minutes (healthy)   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   solectrus-app-1
e589fdfeb50b   ghcr.io/solectrus/senec-collector:latest      "/bin/sh -c 'bundle …"   About an hour ago   Up 15 minutes                                                         solectrus-senec-collector-1
28a6a0bc7cbd   ghcr.io/solectrus/forecast-collector:latest   "/bin/sh -c 'bundle …"   About an hour ago   Up Less than a second                                                 solectrus-forecast-collector-1
3b928d2ab016   influxdb:2.6-alpine                           "/entrypoint.sh infl…"   About an hour ago   Up 15 minutes             8086/tcp                                    solectrus-influxdb-1
86a3191aee25   postgres:15-alpine                            "docker-entrypoint.s…"   About an hour ago   Up 15 minutes             5432/tcp                                    solectrus-db-1
be4c6c74f292   redis:7-alpine                                "docker-entrypoint.s…"   About an hour ago   Up 15 minutes             6379/tcp                                    solectrus-redis-1
root@pi64:/home/pi/solectrus#

**Comment by ledermann** [comment]
Seltsam. Alle Container laufen, InfluxDB verweigert jedoch den Zugriff. Ich vermute ein Problem mit dem Token für InfluxDB. Bitte poste noch den Output von folgenden **zwei** Befehlen, um die Umgebungsvariablen zu sehen:

```
docker exec solectrus-senec-collector-1 /bin/sh -c /usr/bin/env
docker exec solectrus-influxdb-1 /bin/sh -c /usr/bin/env
```

Außerdem: Wie genau hast Du das Update durchgeführt? Oder fand das automatisch statt, z.B. mit WatchTower? Hast Du seit dem letzten Container-Neustart von SOLECTRUS, der möglicherweise schon länger her ist, etwas an der `docker-compose` oder der `.env`-Datei verändert? Solche Änderungen würden sich erst jetzt auswirken.

**Comment by TheBrain8788** [comment]
root@pi64:/home/pi/solectrus# docker exec solectrus-senec-collector-1 /bin/sh -c /usr/bin/env
RUBY_MAJOR=3.2
SENEC_HOST=192.168.2.118
HOSTNAME=e589fdfeb50b
SHLVL=1
HOME=/root
BUNDLE_APP_CONFIG=/usr/local/bundle
BUILDTIME=2023-03-23T14:54:51.458Z
INFLUX_TOKEN=my-super-secret-admin-token
INFLUX_ORG=solectrus
VERSION=0.7.0
RUBY_VERSION=3.2.1
PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
INFLUX_SCHEMA=http
SENEC_INTERVAL=5
INFLUX_HOST=influxdb
LANG=C.UTF-8
REVISION=c462b6d70db871a544183d6759dbea130ecc4409
GEM_HOME=/usr/local/bundle
INFLUX_PORT=8086
RUBY_DOWNLOAD_SHA256=746c8661ae25449cbdc5297d1092702e93e66f365a75fecb740d4f292ced630c
MALLOC_ARENA_MAX=2
PWD=/senec-collector
INFLUX_BUCKET=my-solectrus-bucket
BUNDLE_SILENCE_ROOT_WARNING=1
root@pi64:/home/pi/solectrus#



root@pi64:/home/pi/solectrus# docker exec solectrus-influxdb-1 /bin/sh -c /usr/bin/env
HOSTNAME=3b928d2ab016
SHLVL=1
HOME=/root
DOCKER_INFLUXDB_INIT_BUCKET=my-solectrus-bucket
DOCKER_INFLUXDB_INIT_MODE=setup
DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-admin-token
DOCKER_INFLUXDB_INIT_USERNAME=admin
INFLUX_CLI_VERSION=2.6.1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
INFLUXD_INIT_PING_ATTEMPTS=600
DOCKER_INFLUXDB_INIT_ORG=solectrus
INFLUXD_INIT_PORT=9999
PWD=/
DOCKER_INFLUXDB_INIT_CLI_CONFIG_NAME=default
DOCKER_INFLUXDB_INIT_PASSWORD=ExAmPl3PA55W0rD
INFLUX_CONFIGS_PATH=/etc/influxdb2/influx-configs
INFLUXDB_VERSION=2.6.1
root@pi64:/home/pi/solectrus#



Update über docker compose pull

ich habe in der .env lediglich die IP des pi4 nachtäglich geändert vor ein paar Tagen.

**Comment by ledermann** [comment]
Sieht alles korrekt aus. Eine Lösung ist leider noch nicht in Sicht. 

Prüfen wir erst mal, ob das Token noch funktioniert:
```
docker exec -it solectrus-influxdb-1 influx auth list -t "my-super-secret-admin-token"
```

Wenn das funktioniert, dann die User sowie die Buckets in InfluxDB auflisten:
```
docker exec -it solectrus-influxdb-1 influx user list -t "my-super-secret-admin-token"
docker exec -it solectrus-influxdb-1 influx bucket list -t "my-super-secret-admin-token" -o solectrus
```

Welcher Output erscheint jeweils?

**Comment by TheBrain8788** [comment]
root@pi64:/home/pi/solectrus# docker exec -it solectrus-influxdb-1 influx auth list -t "my-super-secret-admin-token"
Error: could not find authorization with given parameters: 401 Unauthorized: unauthorized access
root@pi64:/home/pi/solectrus#

**Comment by ledermann** [comment]
Wie es scheint, erlaubt das Admin-Token keinen Zugriff mehr auf InfluxDB. Ich kann mir derzeitig nicht erklären, wie das entstanden ist. Irgendetwas ist mit dem InfluxDB-Container geschehen. Mit SOLECTRUS hat es eher nichts zu tun und insbesondere auch nicht mit dem Update auf die Version 0.10.0.

Leider fehlt mir jetzt auch die Zeit, tiefer in das Problem einzusteigen. Du könntest versuchen, ein neues Influx-Token zu erstellen, was dann aber wohl über das Frontend von InfluxDB geschehen muss, wozu wiederum zunächst Port 8086 nach außen geöffnet werden muss.

Falls mir später noch eine einfachere Lösung einfällt, melde ich mich wieder.

**Comment by TheBrain8788** [comment]
Ich kann die influxd.bolt im Klartext sehen, nur leider vestehe ich nicht wo sich der Token befindet und wo er in der .env ist? hier steht ja immer my-super-secret.....

**Comment by ledermann** [comment]
Das Token befindet sich ziemlich am Anfang dieser Datei, siehe mein Beispiel, da steht ja das "my-super-secret-admin-token". Vermutlich steht da bei Dir jetzt ein anderes. Kommt es Dir bekannt vor? Hast Du es selbst angelegt? 

In der `.env`-Datei müsste es überall da eingetragen werden, wo derzeitig "my-super-secret-admin-token" steht, zumindest aber bei den Variablen `INFLUX_TOKEN_WRITE` und `INFLUX_TOKEN_READ`.

**Comment by TheBrain8788** [comment]
0ae99xxxxxxxxxx{"id":"0ae99xxxxxxxxxxxxx","token"

ist also 0ae99..... der Token?

**Comment by ledermann** [comment]
Nein, ein paar Buchstaben dahinter, das Ding hinter `"token":`

**Comment by TheBrain8788** [comment]
OK das war es! Läuft wieder.

Nur komsich das ich nie in der .env oder in der influxd.bolt einen Token eingefügt bzw, geändert hatte?!

**Comment by ledermann** [comment]
Großartig! 

Was da bei Dir passiert ist, kann ich leider auch nicht sagen. In der Installationsanleitung wird nur ein einziges Token, das "my-super-secret-admin-token" angelegt, das dann überall verwendet wird. Das Token wird beim ersten Start von InfluxDB festgeschrieben und dann auch nicht mehr geändert. 

Man kann natürlich selbst auf verschiedenen Wegen Zugriffs-Token neu anlegen oder löschen. Aber das macht man eigentlich nicht versehentlich.

Da das Problem gelöst ist und ich nicht wüsste, was ich zur zukünftigen Vermeidung verbessern könnte, schließe ich das Issue.
