### ISSUE TITLE
Tooltip wird nicht aktualisiert

### ISSUE THREAD

**Issue by GuenniAC** [solectrus/solectrus#1886]
Unterschiedliche Angaben für Hausverbrauch wenn "Mouse-over" Feld, siehe Anhang
![2023-04-03_14-18](https://user-images.githubusercontent.com/113255261/229509579-ff2a7a09-1bfa-476b-bb89-e68d63b2012e.png)

**Comment by ledermann** [comment]
Ja, das ist ein Darstellungsfehler. Danke fürs Melden!

Ursache ist die automatische Aktualisierung per AJAX alle 5 Sekunden im Browser, die für Tooltips nicht so recht funktioniert, d.h. der vorherige Tooltip bleibt bestehen. Mache einen Full-Reload (Browser-Refresh), dann stimmt es wieder.

Ich werde das korrigieren.

**Comment by ledermann** [comment]
Dieser Bug ist nun endlich behoben, die Tooltips werden jetzt bei jeder neuen Messung mit aktualisiert.

Die Korrektur fließt ins kommende Update mit ein. In der [Live-Demo](https://demo.solectrus.de/house_power/now) ist sie bereits enthalten.
