### ISSUE TITLE
Top10-Wert für aktuellen Zeitraum manchmal ungenau

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#1894]
### Discussed in https://github.com/orgs/solectrus/discussions/1888

Wenn der aktuelle und noch nicht beendete Tag, Monat, Jahr in den Top-10 vorkommt, ist dessen Wert manchmal etwas zu hoch. Ursache ist vermutlich die verwendete InfluxDB-Abfrage, die zu einer Hochrechnung führt.

**Comment by ledermann** [comment]
Ursache ist, dass mit Flux die Verwendung von `aggregateWindow(every: 1h, fn: mean)` ungenau ist, wenn der Zeitraum noch nicht abgeschlossen ist.

Lösungsansatz: 

- Statt einer Top10 intern eine Top11 berechnet
- Wenn auf den ersten 10 Plätzen der aktuelle Zeitraum vorkommt, diesen zusätzlich separat berechnen (über `PowerSum`), Wert austauschen, neu sortieren (alle 11) und die ersten 10 nehmen

**Comment by AlpenFlizzer** [comment]
Ich stolpere selbst gerade wieder über diesen Umstand. 
Ich habe eine neue Solectrus Instanz die heute den ersten Tag speichert.
In allen Timeframe Tabs werden verschiedene Werte angezeigt. Ich verstehe, dass es an unvollständigen Tagen wegen der Flux zu ungenauem Verhalten kommt, aber bedeutet das, dass ich jetzt warten muss, bis diese Woche, Monat, Jahr, zukünftige Jahre immer erst vollständig sein müssen, damit sie korrekt dargestellt werden? Oder heißt das bei meiner neuen Instanz, dass ab morgen die Anzeigen korrekt sind, wenn der erste Tag im Kasten ist?

Eventuell könnte man den Umstand noch in FAQs aufnehmen/beschreiben, da der Weg zu dem Issue recht verschachtelt war und es mehrfach-Issues zum selbenm Thema, wenn auch mit Abwandlungen, gibt. Ich hätte auch keine Erwähnung entdeckt, wie weit eine Lösung entfernt ist oder wie nah.

Danke für eure Hilfe!

**Comment by ledermann** [comment]
@AlpenFlizzer Meinst du wirklich die Top10? Wenn ja: Das ist leider ein bekanntes Problem, eine Lösung habe ich oben (3. Juli) skizziert, aber noch nicht implementiert.

Es ist so: Wenn deine Instanz heute den ersten Tag aufgezeichnet hat (aber noch nicht vollständig, da der 28. August noch nicht vorbei ist) und du die Top10 für Tag aufrufst, dann wird diese nicht exakt den richtigen Wert anzeigen. Rufst du dann morgen die Top10 für Tag auf, wird der 28. August korrekt angezeigt. Dann wird jedoch der Wert vom 29. August nicht exakt sein. So geht es weiter, bis irgendwann der aktuelle Tag nicht mehr in der Top10 vorhanden ist.

Am Anfang, wenn die Instanz erst seit kurzem läuft, hat die Top10 sowies keine besondere Aussagekraft. Mit der Zeit justiert sich das dann. Nach einer gewissen Zeit ist die aktuelle Periode sowie nur noch sehr selten enthalten, das Problem verschwindet dann quasi.

Dennoch ist eine Korrektur natürlich noch geplant. Ggfs. könnte ich auch eine einfachere Lösung implementieren und die aktuelle Periode grundsätzlich gar nicht in der Top10 anzeigen. Also so, wie es auch bei der Flop10 gemacht wird.

Korrekt ist übrigens immer die Strombilanz, also wenn du dort den betreffenden Zeitraum aufrufst. Das ist der Vergleichsmaßstab.

**Comment by AlpenFlizzer** [comment]
Ich meine die Strombilanz, habe mich bloß wegen der Artverwandtschaft an diesen Issue angehängt.
Ich zeige mal das Problem:
![grafik](https://github.com/user-attachments/assets/6a3b97a8-5852-4ab6-93c7-a28eabbc3471)

Wie schon erwähnt ist das eine Solectrus Instanz die ich seit heute frisch füttere. Nach einigen Setup Problemen habe ich den Influx Container und die Daten im Bind-Mount gelöscht und mit der Speicherung neu begonnen. Kann das ein Probem sein?
Das Bild ist demonstrativ, ich habe ähnliche Abweichungen bei den anderen Sensoren auch.

Die Daten kommen alle 5 Sekunden via MQTT daher. Ich hatte bei meiner ersten Instanz ebenfalls komische Probleme mit den historischen Daten aus Solaredge, damals lag es daran, dass die Datenpunkte wohl nicht zu einem erwarteten Zeitintervall gepasst haben.
