### ISSUE TITLE
Messpunkte in Grafiken bleiben stehen

### ISSUE THREAD

**Issue by Zeppelin-PV** [solectrus/solectrus#1896]
Fährt man eine Grafik mit dem Cursor langsam ab bleiben vereinzelte Messpunkte stehen.
Sowohl mit Firefox als auch mit Chrome (Windows)

nachträgliche Feststellung: wenn ein Messpunkt angezeigt wird und von rechts die Grafik erneuert wird (5sec.) bleibt dieser Punkt stehen. 

![Messpunkte](https://user-images.githubusercontent.com/126392805/230332885-783bcb23-7327-4a62-9b67-bbea04a8443f.jpg)

Ergänzung 14.4.22
die Anzeigewerte der Null-Linie sind eigentlich überflüssig und könnten ignoriert werden
somit wäre auch die Anzeige-Box bei den relevanten Werten 
das widerum würde bedeuten, dass die Grafiken Netz und Akku getrennt werden müssten in "Bezug" und "Einspeisung"
bzw, "Beladen" und "Entnahme"

**Comment by ledermann** [comment]
Ja, dieses kosmetische Problem tritt auf der JETZT-Seite auf, wenn ein neuer Messpunkt ergänzt wird, während der Nutzer gerade das Diagramm mit der Maus "abfährt". 

Ich bin mir noch nicht sicher, ob ich darauf Einfluss habe oder ob das ein Fehler in der verwendeten Chart-Library ist.

**Comment by ledermann** [comment]
Mittlerweile (nach einigen Updates von Chart.js) scheint das Problem nicht mehr aufzutreten, zumindest kann ich es nicht mehr reproduzieren. Somit schließe ich das Issue.
