### ISSUE TITLE
Show forecast for more days

### ISSUE THREAD

**Issue by Bart1909** [solectrus/solectrus#1898]
Hi @ledermann,

With a paid forecast api key you can get the forecast data for +3 or even +6 days.
The solectrus dashboard shows only the next day.

It would be nice, if more days are shown.

Best regards

Tobi

**Comment by ledermann** [comment]
Good hint, that was easy to implement. Will be included in the next update.

**Comment by ledermann** [comment]
Available now as part of version v0.10.1

**Comment by Bart1909** [comment]
Working fine :)

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/14097923/236613551-8e99f411-45b0-42fc-8217-7a12f38ba13e.png">

**Comment by noffycws** [comment]
Is there a documentation, how to integrate the forecast api key in Solectrus?

**Comment by ledermann** [comment]
Hm, the [Forecast Collector](https://github.com/solectrus/forecast-collector) currently doesn't support specifying an API key at all. Of course, I could add this, but I'm curious how @Bart1909 did it.

**Comment by Bart1909** [comment]
I modified the source code of the quarkus-forecast-collector and implemented the api key in the request url:
https://github.com/jbaesner/quarkus-forecast-collector/blob/d389342e573cbc7384b9d93e6f45294b690f08fd/src/main/java/org/solectrus/ForcastSolarApp.java#L64

I modified this line to:
`baseUrl = "https://api.forecast.solar/<myApiKey>";`

**Comment by Bart1909** [comment]
Good to know: as mentioned [here](https://github.com/solectrus/forecast-collector/issues/64) I do not use the solectrus collector but instead use the [quarkus-forecast-collector](https://github.com/jbaesner/quarkus-forecast-collector/tree/main)

**Comment by noffycws** [comment]
It is described here: https://doc.forecast.solar/api:estimate
There is an URL :apikey. With this key you can access to the paid functions.

@ledermann: Maybe you can add an variable FORECAST_APIKEY in the .env and use this in the forecast-collector.

**Comment by ledermann** [comment]
Ok, thanks @Bart1909 and @noffycws for clarification.

I will add support for the API key in the near future, there is already an issue for this:
https://github.com/solectrus/forecast-collector/issues/72
