### ISSUE TITLE
Kennzahlen in Kachel-Darstellung

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#1986]
Alternativ zur jetzigen Darstellung könnte es nützlich sein, eine weitere Seite zu haben, auf der ohne Diagramm nur einige wichtige Kennzahlen ersichtlich sind, beispielsweise:

- PV-Erzeugung Jetzt
- PV-Erzeugung Tag
- Akkustand Jetzt
- Temperatur Jetzt
- Ersparnis Tag

Die Darstellung könnte über Kacheln erfolgen. Einzelne Werte könnten als Tacho visualisiert werden.

**Comment by StevieC121176** [comment]
Finde ich auch eine sehr gute Idee. Genial wäre das noch als Widget fürs Telefon. Ich habe mal im OpenWB Forum etwas gefunden. Diese Wallbox kann auch PV Monitoring. Dort hat ein User diese anpassbaren Widgets erstellt. Vielleicht könnte man so etwas ähnliches für Solectrus implementieren.
![B4C07331-6127-448B-9742-0B12750D2914](https://github.com/solectrus/solectrus/assets/113791299/bd1600e5-f0fe-4458-b40c-53baa5fc47e2)
<img width="375" alt="Statistik_widgets-2" src="https://github.com/solectrus/solectrus/assets/113791299/6cca63e0-fa3b-476f-8893-479bff308f81">

![AC845947-1332-4C69-B245-FCA52DDEEE7D](https://github.com/solectrus/solectrus/assets/113791299/4d11dac6-bf5b-46d4-8cf0-909c36ebba5a)
![717B36A6-7E0C-4221-8A73-FEA155FFE0AA](https://github.com/solectrus/solectrus/assets/113791299/f277cc7d-f047-4deb-94cf-acd995c830bc)

**Comment by halmich** [comment]
gute Idee :)

**Comment by StevieC121176** [comment]
Ich habe mich mal etwas mit den Widgets in IOS beschäftigt. So wie es scheint werden die Daten nicht aktuell dargestellt sondern die sind teilweise schon etliche Minuten alt. Das ist eher suboptimal.

von daher wäre eine Browserbasiertes Darstellung mit zeitnaher Darstellung der Livedaten besser. Ich habe mal ein Beispiel erstellt. Dieses ist Grafana basiert mit den Daten aus der influxdb
Vielleicht wäre sowas etwas für eine 2. Seite in Solectrus.
Das ist jetzt die mobile Darstellung, funktioniert hat. auch mit der Desktop Variante

![IMG_0935](https://github.com/solectrus/solectrus/assets/113791299/93d74669-dfc3-437d-ae59-ac28cfbb13e3)

**Comment by ledermann** [comment]
Für dieses Issue hat sich mittlerweile ein Sponsor gefunden, der die Entwicklung finanziert :) 
Ich arbeite somit jetzt an der Implementierung, in der Live-Demo ist bereits etwas zu sehen. 

Die Kacheldarstellung ist zunächst allerdings fix, d.h. es gibt keinerlei Anpassungsmöglichkeit und es gibt auch keine integrierten Charts oder Tacho-Darstellungen. Das wären zukünftige Ausbaustufen.

**Comment by StevieC121176** [comment]
Super. Auch das kleine Pulsieren des Wertes wenn er sich aktualisiert ist schick gemacht 👍 
Da bin ich schon gespannt wie das in Zukunft wird. 
Vielleicht könnte man die Anzeigewerte konfigurierter machen evtl. über eine Auswahlliste.
Solectrus wird immer besser.

**Comment by ledermann** [comment]
Das Pulsieren war das Schwierigste ;-) 

Eine Konfiguration der Darstellung wird unvermeidlich sein, völlig klar. Jeder möchte da andere Dinge sehen. Aber das kommt später.

**Comment by StevieC121176** [comment]
Unter IOS17 wird passt die Ansicht nicht ganz auf das Display. Evtl. könnte man die Kacheln  noch etwas in der Höhe kürzen das 6 Kacheln auf das Display passen?

![IMG_1831](https://github.com/solectrus/solectrus/assets/113791299/d718a44c-264a-4697-a4f8-6b0f395e4fdc)

**Comment by ledermann** [comment]
Ja, ist bekannt, das Layout passt sich noch nicht ideal an die Höhe an. Kümmere ich mich noch drum. Ist alles noch im Fluss, der jetzige Stand ist nur der erste Wurf.

**Comment by StevieC121176** [comment]
Cooles Icon für "Einsparung" 👍 :-)

**Comment by ledermann** [comment]
Die Kacheln sind nun im develop-Image verfügbar. Feedback willkommen. Wenn jemand Fehler feststellt, bitte neues Issue anlegen. Es werden einige neuere Browser-Fähigkeiten genutzt ("Container Queries" und "Dynamic viewport units"), denkbar sind also Probleme mit älteren Browsern.

Zum Thema Customizing habe ich schon mal das Issue #2511 angelegt. Das wird aber vermutlich nicht kurzfristig realisiert werden - es sei denn, es findet sich ein weiterer Sponsor ;-)

**Comment by Bart1909** [comment]
Moin @ledermann,
coole Ansicht, gefällt mir auch :)

Ich frag mich nur, was der Wert darstellen soll:
![grafik](https://github.com/solectrus/solectrus/assets/14097923/c99f3d2e-0e5a-4079-a29f-5c7730d728bc)

Es gibt keinen Hover-Text dazu und bei einem Klick darauf öffnet sich die Jahresansicht, wo ich den Wert aber nicht wiederfinde.

Vielleicht könnte man da noch eine Erklärung dran packen?

Viele Grüße

Tobi

**Comment by ledermann** [comment]
@Bart1909 Das ist die CO₂-Einsparung in Tonnen, derzeitig nur auf der Einzelwerte-Ansicht dargestellt - und ja, hast recht, das muss noch besser herausgestellt werden. Habe #2594 angelegt.

Überhaupt wird sich diese Seite noch weiter verbessern, das ist nur eine erste Fassung :-)
