### ISSUE TITLE
Wrong values in hover for 'today' in 'week' and 'month' overview...

### ISSUE THREAD

**Issue by jbaesner** [solectrus/solectrus#2032]
When looking at the current data from _today_, e. g.:

![image](https://github.com/solectrus/solectrus/assets/5062496/5a1a7c88-22b7-41d1-8b7d-099bedf38819)

The values are _in sync_ with what the SENEC App displays at that time, but switching to the _week_ or _month_ overview for _today_, the hover for today shows a wrong value, see:

**week:**
![image](https://github.com/solectrus/solectrus/assets/5062496/f37d8473-b613-427a-91eb-df9a738eec8e)

**month:**
![image](https://github.com/solectrus/solectrus/assets/5062496/8193de74-425d-45cc-828c-d36c5c2d4eb6)

This example shows the _production_, but it's the same for other types as well...

When using hovering past days, the values are correct.

**Comment by ledermann** [comment]
You are right. The column in the diagram for the current day (or week/month/year) is **not correct**. However, this is only a temporary deviation. As soon as the day is over, it will be correct again. It's caused by the way InfluxDB handles incomplete data.

I already noticed this in the past, but I never wrote it down because the error always corrects itself. Thank you for finally doing it :-)

I'll see how I can fix that.

**Comment by ledermann** [comment]
#1894 describes a similar problem. The reason for both issues is that the InfluxDB query used by SOLECTRUS can be inaccurate for non-closed time ranges. 

Tech details: I use this aggregation code, which has great performance. But, it doesn't work right when there's not a full hour of data. I can't find a function in InfluxDB that can fix this concern.

```
|> aggregateWindow(every: 1h, fn: mean)
|> aggregateWindow(every: 1d, fn: sum)
```

I have not found a solution to this issue yet, unfortunately. As soon as InfluxDB 3.0 is available, I'll take another look at the issue.

**Comment by ledermann** [comment]
Ursache ist, dass mit Flux die Verwendung von `aggregateWindow(every: 1h, fn: mean)` ungenau ist, wenn der Zeitraum noch nicht abgeschlossen ist.

Lösungsansatz: 

Wenn das dargestellte Diagramm einen nicht abgeschlossenen Zeitraum betrifft (also aktuelle Woche/Monat/Jahr oder Gesamt), dann Sonderbehandlung mittels Split:

1. Zunächst abgeschlossenen Zeitraum wie bisher berechnen
2. Zusätzlich den laufenden (noch nicht abgeschlossenen Zeitraum) genau berechnen, über `integral(unit: 1h)`, mit [PowerSum](https://github.com/solectrus/solectrus/blob/develop/app/services/power_sum.rb)

Beispiel für die Berechnung des Diagramms für Juni 2024 am 14. Juni:

1. Diagramm für den Zeitraum vom 1. Juni bis 13. Juni wie bisher berechnen
2. Tag des 14. Juni mittels `PowerSum` berechnen

Das hat auch positive Auswirkungen auf die Performance, weil die Abfragen für abgeschlossene Zeiträume im Cache landen.
