### ISSUE TITLE
Differenz Anzeige Erzeugung Tag und Top 10 Tag

### ISSUE THREAD

**Issue by StevieC121176** [solectrus/solectrus#2076]
Mir ist aufgefallen das der angezeigte Wert für die Erzeugung zum gleichen Zeitpunkt in der Top 10 Anzeige und in der Anzeige Verlauf Tag abweichen. Der Top 10 Wert ist höher als der tatsächliche Wert für die Erzeugung. sh. Screenshots (beide zur gleichen Zeit)

<details>
 <summary>Screenshots</summary>

![IMG_0825](https://github.com/solectrus/solectrus/assets/113791299/b2b658b9-bf28-4c1c-8b19-f8f74ac9710e)
![IMG_0826](https://github.com/solectrus/solectrus/assets/113791299/510f939d-9161-4bf9-89ef-bd65c5214c06)

<details>

**Comment by ledermann** [comment]
Ja, das ist ein bekanntes Problem, siehe #1894.
