### ISSUE TITLE
Falsche Aufsummierung der Jahre --> Gesamt

### ISSUE THREAD

**Issue by derheinrich2019** [solectrus/solectrus#2107]
Das selectrus-Dashboard wurde erfolgreich in der Verwandschaft installiert ;)

Jetzt haben wir auch die bisherigen Daten über den Senec-Importer in das Dashboard geholt. Hat alles Dank der sehr guten Anleitung ohne Probleme funktioniert.

Beim ersten Durchschauen der Daten ist folgendes aufgefallen:

Die Gesamtsumme bei "Einsparung" ist bei der Addition der beiden Jahre 2022 und 2023 falsch. Oder spielt da ggfs. noch ein anderer Parameter rein? Für die "Kosten" ist es korrekt.

Im Anhang die beiden Jahre und die Gesamtzahlen.

Tolles Projekt! 

![2023-06-22_15-32](https://github.com/solectrus/solectrus/assets/52661926/8226bdb6-a7f8-4959-90ad-3e3f916cb4bd)
![2023-06-22_15-32_1](https://github.com/solectrus/solectrus/assets/52661926/a9d8f6db-32f2-4250-bdec-f61133df9707)
![2023-06-22_15-32_2](https://github.com/solectrus/solectrus/assets/52661926/50dfda40-7ba2-4c54-9395-cde0415d1381)

**Comment by derheinrich2019** [comment]
Beim Einstellen der Bilder ist mir aufgefallen, dass die Werte für Einspeisung, Erzeugung und Akku-Beladung auch nicht stimmen. Strombezug und Akku-Entladung sind richtig.

**Comment by ledermann** [comment]
Möglicherweise vergessen, nach dem Import den Redis-Cache zu löschen?
Siehe hier: https://github.com/solectrus/senec-importer#usage

**Comment by ledermann** [comment]
Ok, andere Idee: `INSTALLATION_DATE` in der `.env` korrekt? Nach Änderung muss der App-Container neu gestartet werden.

**Comment by derheinrich2019** [comment]
OK. "Fehler" lag woanders.
Installationsdatum in der .env war korrekt gesetzt. Jedoch in der GUI über Einstellungen --> Gültig ab lag vor dem Installationsdatum in der env.. Geändert und die Zahlen stimmen.

Besten Dank für deine schnelle Hilfe!

**Comment by ledermann** [comment]
Gut, dass es nun funktioniert. Die Ursache kann ich aber nicht ganz nachvollziehen. Selbst wenn ein Strompreis zeitlich **vor** dem Installationsdatum liegt, hat das keine negative Auswirkung auf die Berechnung, dieser Fall wird explizit behandelt. Außerdem würde es nicht erklären, warum Erzeugung und andere kWh-Werte nicht zusammenpassen. 

Aus meiner Sicht deutet alles auf ein Caching-Problem bzw. einen nicht oder nicht richtig gelöschten Cache hin.

Aber egal, belassen wir es dabei und freuen uns, dass nun alles stimmt ;-)
