### ISSUE TITLE
Kosten / Einsparung - schwäbische Anzeige

### ISSUE THREAD

**Issue by Zeppelin-PV** [solectrus/solectrus#2138]
hallo Georg
könnte man den Schwaben zuliebe bei der Kosten/Einsparung Anzeige auch die zwei Kommastellen Cent anzeigen ?
... auch den NichtSchwaben zuliebe
LG
Ernst /Zeppelin-PV

**Comment by ledermann** [comment]
Mir ist nicht ganz klar, was Du hier meinst. Grundsätzlich ist es so, dass SOLECTRUS bei großen Zahlen (kWh oder €) die Nachkommastellen weglässt. Das halte ich eigentlich auch für richtig und sinnvoll.

Hier ein Beispiel, [Monat Juni 2023 aus der Live-Demo](https://solectrus.ledermann.dev/inverter_power/2023-06):

<img width="209" alt="Juni 2023" src="https://github.com/solectrus/solectrus/assets/3557/acbd0b02-cea7-45d8-83fe-87ac61405f58">

Die Kosten sind hier sehr gering, daher werden sie **mit** Nachkommastellen angegeben. Die Einsparung ist hingegen sehr hoch, daher werden die Cents **nicht** angegeben. 

Ich möchte Zahlenwüsten vermeiden. Ansonsten denke ich bei dem Thema immer an meinen alten Physik-Lehrer, der meinte: "Suggeriere keine Genauigkeit durch viele Nachkommastellen, wenn Du gar nicht so genau messen kannst!"

**Comment by Zeppelin-PV** [comment]
bis Monat sind die Cents da, im Jahr und Gesamt nicht, aber ...
... Dein Physik-Lehrer hat recht !!!
Issue schließen

**Comment by ledermann** [comment]
Ok, wir belassen es so.

Nur der Vollständigkeit halber: Es hat nichts mit dem Zeitraum zu tun, sondern nur mit der Zahl. Unter 10 € gibt es Nachkommastellen, ansonsten nicht.
