### ISSUE TITLE
"Einspeisung" ohne Quelle 

### ISSUE THREAD

**Issue by spyro2000** [solectrus/solectrus#2174]
Insbesondere nach höheren Lasten, die direkt aus dem Akku bedient werden, erhalte ich oft Werte wie folgt:

![Screenshot_2023-07-13-22-01-43-16_4d38fce200f96aeac5e860e739312e76](https://github.com/solectrus/solectrus/assets/8479925/011621e3-e2f5-4e78-810e-2d0bc7a711ec)

Obwohl es längst dunkel ist, wird hier eine Einspeisung angezeigt, die auch auf der linken Seite nicht auftaucht.

Und warum ist der Entnahmewert größer als der Hausverbrauch? Wird hier wirklich Leistung direkt aus dem Akku in das Netz eingespeist (bei Senec wundert mich nichts mehr...)? 

Datenquelle ist ein Senec Home v2.

**Comment by ledermann** [comment]
Ich denke, das liegt in der Trägheit des Speichers begründet: 

Dein Hausverbrauch hat, wie man im Diagramm sehen kann, gerade eine höhere Last verursacht, die dann aus dem Speicher gedeckt wurde. Dann hat der Verbraucher **abgeschaltet**, der Speicher liefert aber noch ein paar Sekunden die höhere Leistung, bevor er das "merkt". Und da der Strom irgendwo hin muss, wird er eben eingespeist. Insofern: Ja, es erfolgt eine (kurze) Einspeisung aus dem Akku ins Netz. Analog erfolgt beim **Einschalten** eines starken Verbrauchers auch ein kurzer Netzbezug, bevor der Speicher reagiert und liefert.

Ob andere Hersteller dies anders handhaben und ob das überhaupt möglich ist, weiß ich nicht. Meinen Beobachtungen zufolge hat das aber nur minimale Auswirkungen.

**Comment by spyro2000** [comment]
Ahh, verstehe, danke für die Aufklärung! :)
Hätte nicht gedacht, dass das gleich mehrere Minuten dauert.

**Comment by ledermann** [comment]
Soweit ich das bei meinem V3-Speicher beobachten kann, sind das immer nur wenige Sekunden. Nicht Minuten.

**Comment by Zeppelin-PV** [comment]
ja, das habe ich auch schon beobachtet und festgestellt dass es sich wirklich um ein paar Sekunden handelt
steht man bei diesem Regelverhalten direkt am Speicher laufen die LEDs von oben nach unten und queerbeet (wie in der Disco)
die Anzeige am Speicher ist 500ms schnell
