### ISSUE TITLE
wrong values in battery load diagram

### ISSUE THREAD

**Issue by iot-sle** [solectrus/solectrus#2205]
the values in battery load diagram are correct just after a refresh. When the continuesly shown values are wrong.
Tested on differnt platforms.
![image](https://github.com/solectrus/solectrus/assets/74416643/e38e1194-5c53-45e3-a75e-def705693d31)
Same behavior for autarky / temperature / usage

**Comment by ledermann** [comment]
Good catch! Will fix this soon...

**Comment by ledermann** [comment]
Just resolved this issue, see live demo:
https://solectrus.ledermann.dev/case_temp/now

Will be included in the upcoming update.
