### ISSUE TITLE
Balkendiagramme mit abgerundeten Ecken

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#2213]
> Eine Kleinigkeit zur Optik: Bei der Anzeige Verwendung und Herkunft sind die Ecken leicht abgerundet dargestellt. Vielleicht wäre das bei den Balkendiagrammen auch möglich und würde diese etwas "weicher" aussehen lassen. Als Beispiel hier die Small radius Balken bei Charts.js. https://www.chartjs.org/docs/latest/samples/bar/border-radius.html

_Originally posted by @StevieC121176 in https://github.com/solectrus/solectrus/issues/1881#issuecomment-1656038026_

**Comment by ledermann** [comment]
@StevieC121176 Ja, abgerundete Ecken gibt es in SOLECTRUS überall, daher sollte das auch für die Balken gelten. 

Ich habe das gerade erledigt, es wird ins nächste Update einfließen. In der Live-Demo ist es bereits jetzt zu sehen: https://solectrus.ledermann.dev/grid_power/2023-W30

**Comment by StevieC121176** [comment]
Sieht sehr gut aus, vielen Dank.
