### ISSUE TITLE
Minor Nitpick: Zahlenformatierung im Chart-Mouseover

### ISSUE THREAD

**Issue by gereons** [solectrus/solectrus#2222]
In den Chart-Mouseovers werden Zahlen "englisch" mit Dezimalpunkt und Tausenderkomma statt mit Dezimalkomma und Tausenderpunkt formatiert.

<img width="423" alt="screenshot" src="https://github.com/solectrus/solectrus/assets/2861931/12882b07-1e90-499a-b93d-93294d2b4e28">

**Comment by ledermann** [comment]
Interessant, bei mir (Firefox/Chrome/Safari, Sprache=DE) sieht es korrekt aus:

<img width="564" alt="solectrus-tooltip" src="https://github.com/solectrus/solectrus/assets/3557/227f0dfb-6415-44d9-803a-73020a413a04">

Für die Formatierung verwende ich [Intl.NumberFormat().format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat), wodurch es dem Browser überlassen wird, wie genau das Ergebnis aussieht.

Welchen Browser verwendest Du denn? Hast Du besondere Spracheinstellungen im Browser vorgenommen? Tritt das gleiche Phänomen bei Dir auch in anderen Browsern auf?

**Comment by gereons** [comment]
Tatsächlich passiert das nur in Firefox; Safari und Chrome sind OK, die benutze ich nur so gut wie nie. Ich wüsste im Moment nicht was oder wie ich an den Locale-Einstellungen im FF gedreht haben sollte. Das UI von Firefox ist jedenfalls deutsch... Danke für den Hinweis schonmal.

**Comment by gereons** [comment]
Ah, habs gefunden. Aus mir unbekannten Gründen war in meinem FF-Profil `javascript.use_us_english_locale = true` gesetzt, vermutlich durch eine Extension. Löschen der Einstellung hat Abhilfe geschaffen. Danke!

**Comment by ledermann** [comment]
Wow, eine solche Ursache muss man erst mal finden ;-)
