### ISSUE TITLE
Beim Wechsel der Charts wird mit den Daten der vorherigen Quelle weitergezeichnet

### ISSUE THREAD

**Issue by gereons** [solectrus/solectrus#2226]
Folgendes merkwürdige Phänomen ist mir schon vor einigen Tagen aufgefallen, jetzt hab ich einen Weg gefunden es zu reproduzieren:

Angenommen ich schaue mir gerade den "Jetzt"-Chart für die Erzeugung an. Das sah vorhin bei mir so aus:

<img width="469" alt="chart-erzeugung" src="https://github.com/solectrus/solectrus/assets/2861931/2987a02f-c1fa-43d1-a743-10a88aae9b5b">

Also relativ konstant etwas mehr als 3 kWh.

Dann wechsle ich über das Dropdown auf "Hausverbrauch":

<img width="470" alt="chart-verbrauch-1" src="https://github.com/solectrus/solectrus/assets/2861931/5900877a-e96a-4957-8ed2-1584d98b383d">

... und der Chart wird mit den Werten die eigentlich eher zur "Erzeugung" passen weitergemalt.

Klicke ich dann oben in "Verwendung" auf den grauen Abschnitt normalisiert sich der Chart wieder und es geht mit realistischen Verbrauchswerten weiter.

<img width="463" alt="chart-verbrauch-2" src="https://github.com/solectrus/solectrus/assets/2861931/249da955-3f41-4ce8-b294-72ce497d37a1">

Das Problem tritt in Firefox, Safari und Chrome auf.

**Comment by ledermann** [comment]
Danke für die ausführliche Beschreibung, da scheint etwas mit dem Dropdown nicht korrekt zu laufen. Ich kümmere mich darum!

**Comment by ledermann** [comment]
Der Fehler ist nun korrigiert. Beim Wechsel des Diagramms über das Dropdown werden die Messungen korrekt fortgeführt.

Die Korrektur wird im nächsten Update enthalten sein. In der Live-Demo ist es bereits jetzt zu sehen:
https://solectrus.ledermann.dev/inverter_power/now
