### ISSUE TITLE
When using MQTT, the battery is sometimes 0%

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#2238]
I am facing the behaviour that the SOC of the battery show 0% from time to time and then a few mins later jumps back to the actual value:

<img width="592" alt="image" src="https://github.com/solectrus/solectrus/assets/39953358/ec288b21-f64f-4195-aca7-1c9267483ad2">

As far as I remember, this was an issue when the MQTT collector does not get an updated value for some time for this data point. As the ioBroker plugin reads some of the values (e.g. SOC) only every 5 or 10 mins, this might lead to this behaviour.

_Originally posted by @loebse in https://github.com/solectrus/solectrus/discussions/2183#discussioncomment-6635770_

**Comment by ledermann** [comment]
This is now fixed by using a less restrictive InfluxDB query: Instead of getting the last value within 5 minutes only, a much wider range is searched. This achieves that older values are also considered (if no more recent ones are available).

The fix will be available in the upcoming update (probably named `v0.12.1`).

@loebse: Because I'm not using the MQTT collector by myself, maybe you can try this out in your setup and confirm that my fix works. Simply use the `development` image by referencing `ghcr.io/solectrus/solectrus:develop` (instead of `:latest`) in your `docker-compose.yml`.

**Comment by ledermann** [comment]
@loebse: Can you confirm that the bug is fixed (by using the `develop` image)? I would like to release an update in the next few days.

**Comment by loebse** [comment]
I can confirm, it is working now @ledermann!
