### ISSUE TITLE
reset registration token

### ISSUE THREAD

**Issue by ronzle** [solectrus/solectrus#2290]
Hi,

ich habe eine installation, die ich im moment von meinem Home setup ins Rechenzentrum migriert habe. 
Nach der migration habe ich auf v0.13 .0 geupdated.
Dann im DC registriert,
Wenn ich jetzt die derzeitige Home registrieren moechte, kommt das der Token nicht mehr gueltig ist. 
Kann man die Registrierung irgendwie resetten oder einen neuen Token generieren. 

Beide Setups laufen als docker container.
Bei der Migration wurde die Host VM migriert.

Gruss
Ronny

**Comment by ledermann** [comment]
Die Registrierung basiert auf `ID` und `Token`, die zusammenpassen müssen. Beides wird beim ersten Start des App-Containers bestimmt. Das `Token` gibt es aber erst sei Version `0.13` und wird beim ersten Start nach dem Update gewürfelt. Durch das Kopieren einer älteren Version und **nachfolgendem** Update hast du nun zwei Instanzen mit der gleichen `ID`, aber unterschiedlichen `Token`. Somit kann ich das Problem nachvollziehen.

Wenn du dauerhaft beide Instanzen weiter betreiben möchtest, muss also nicht nur das `Token`, sondern auch die `ID` zurückgesetzt werden.

Der einfachste Weg, dies zu tun, ist das Löschen der PostgreSQL-Datenbank, denn dort sind beide abgelegt. Damit verlierst du zwar auch die Strompreise (sonst aber nichts, die Messwerte stehen in InfluxDB), aber die erneut einzutragen ist vermutlich nicht sonderlich aufwendig.

Auf der Instanz, auf der die Fehlermeldung erscheint (bei dir "Home"), ist also Folgendes zu machen:

```bash
docker compose down
cd [solectrus-order]
rm -r postgresql/*
docker compose up -d
```

Falls du das nicht tun möchtest, könnte ich dir ein paar SQL-Befehle konstruieren, mit denen du explizit nur `ID` und `Token` zurücksetzt (die Strompreise also belässt). Das ist aber etwas kniffliger, da ein Zurücksetzen eigentlich gar nicht vorgesehen ist.
