### ISSUE TITLE
autarky circle is missing

### ISSUE THREAD

**Issue by bennysweb** [solectrus/solectrus#2319]
If the feed in is greater then the production, the autarky circle is missing. This special case happens when an additional balcony power plant is connected outside of the senec system. The autarky should be 100% in this case. 

![image](https://github.com/solectrus/solectrus/assets/77127461/56cd4ef2-2c09-4fe7-8151-2a63ee1cfc80)

**Comment by ledermann** [comment]
Thanks a lot, I just fixed it for the next release. The `develop` image is available to try it out.
