### ISSUE TITLE
FAIL + Keine Daten vorhanden!

### ISSUE THREAD

**Issue by Collins1975** [solectrus/solectrus#2327]
Hallo Georg,

Seit 10:15 Uhr heute Vormittag erscheint "FAIL" bei mir und die Anzeige "leuchtet" rot. Die aktuellen Daten werden weiterhin richtig dargestellt nur drunter sehe ich nur "Keine Daten vorhanden!". Ich habe nichts an der Konfiguration geändert?

![image](https://github.com/solectrus/solectrus/assets/104501669/ae9a3dcc-8019-4113-a0f5-2fc301185484)

Unter Tag ist zu sehen das bis 10:20 Uhr alles normal lief:

![image](https://github.com/solectrus/solectrus/assets/104501669/4c2502d2-6f8d-4f53-bab7-b03be8bbbede)

Hast Du eine Idee woran das liegen kann? Solectrus läuft bei mir auf meine Synology v 7.1.1-42962

Vielen Dank im Voraus!

Collins

**Comment by ledermann** [comment]
Sieht so als, als wäre das Update der SENEC-Firmware bei dir angekommen. Hier habe ich dazu etwas aufgeschrieben:

- https://solectrus.de/blog/2023-08-18-unterstuetzung-fuer-neue-senec-firmware/
- https://github.com/orgs/solectrus/discussions/2310

**Comment by Collins1975** [comment]
Hi Georg,

Tja, was soll ich sagen... Wer lesen kann ist klar im Vorteil! Danke für die Info. Ich habe was zu tun!

VG

**Comment by hendrik20062001** [comment]
Moin, ich habe das gleiche Problem, nur das bei mir keine Daten bei Jetzt angezeigt werden. Die Senec Anlage ist noch über HTTP erreichbar.

**Comment by ledermann** [comment]
Erste Anlaufstelle bei derartigen Problemen sind die Logs, hier also die Logs des SENEC-Collectors. Die bekommt man wie folgt:

```
docker logs solectrus-senec-collector-1
```

Alles Weitere häng davon ab, was darin für Fehlermeldungen stehen.

**Comment by niceguy0815** [comment]
Mich hat ma Mitwoch wohl auch das Update erreicht.
SENEC.Home V3 hybrid duo ist jetzt nur noch über https erreichbar.
Hab die genannten Änderungen gemacht und jetzt geht wieder alles DANKE!
![image](https://github.com/solectrus/solectrus/assets/43955022/333880eb-e2fd-4825-9ef2-a27af9e65542)
