### ISSUE TITLE
Unterschiedliche Zeiten Tag/Jetzt

### ISSUE THREAD

**Issue by GerhardPg** [solectrus/solectrus#2374]
In der Grafik zu "Jetzt" geht die X-Achse bis zur aktuellen Uhrzeit (z.B, 13:12) in der Grafik zu "Tag" ist bereits 1,5 Stunden weiter (z.B. 14:50). Habe ich irgendwo etwas falsch konfiguriert, z.B. im .env-File?

**Comment by ledermann** [comment]
Klingt nach einem Zeitzonen-Problem. Hast Du vielleicht vorher Messwerte über den [CSV-Importer](https://github.com/solectrus/csv-importer/) importiert?

Eine Konfiguration, die ein solches Phänomen verursacht, kann ich mir momentan nicht vorstellen. Könntest Du vielleicht noch Screenshots ergänzen, an denen man das sehen kann?

**Comment by ledermann** [comment]
Ich vermute, es handelt sich hier um ein Duplikat von solectrus/csv-importer#88

Falls ja, schließen wir dieses Issue und behandeln das Problem dort.

**Comment by ledermann** [comment]
Ich gehe davon aus, dass es sich um einen Fehler handelt, der durch einen vorherigen CSV-Datenimport in Verbindung mit einem Zeitzonen-Problem ausgelöst wurde. Den CSV-Import habe ich zwischenzeitlich verbessert und aktualisiert. 

Ich schließe das Issue daher. Bitte Bescheid geben, falls das Problem dennoch weiterhin auftreten sollte.
