### ISSUE TITLE
schneller Datumszugriff

### ISSUE THREAD

**Issue by Zeppelin-PV** [solectrus/solectrus#2434]
so was in dieser Art wäre toll für einen schnellen Zugriff auf ein Datum, sogar mit wählbarer Uhrzeit
viele Anwendungen die zeitbasierte Daten verarbeiten nutzen dieses Tool

![grafik](https://github.com/solectrus/solectrus/assets/126392805/f2211773-9b0a-4227-b607-7ace9b4f5d9e)
... der Zeit etwas voraus ;-)

**Comment by ledermann** [comment]
Ja, das wäre zweifellos praktisch und wir haben das bereits in #1931 notiert, daher schließe ich dieses Issue.
