### ISSUE TITLE
Darstellung in iFrame

### ISSUE THREAD

**Issue by BarnyXX** [solectrus/solectrus#2438]
Hi, gibt es eine Möglichkeit Solectrus in einem iFrame darzustellen? Ich bekomme leider die Meldung: Verbindung verweigert.
Hintergrund: Ich möchte Solectrus über meine ioBroker Visualisierung anzeigen.

**Comment by ledermann** [comment]
Das Einbetten in ein `iframe` ist in SOLECTRUS standardmäßig per Content Security Policy (CSP) verboten, daher erhältst du Meldung "... hat die Verbindung abgelehnt" oder ähnlich.

Ich habe aber gerade eine Option ergänzt, um das doch zu ermöglichen: Man legt über die Umgebungsvariable `FRAME_ANCESTORS` fest, in welche Website eine Einbettung erfolgen darf.

Diese neue Option wird im nächsten Update zur Verfügung stehen. Du kannst es aber bereits jetzt   mit dem `develop`-Image ausprobieren.

In `docker-compose.yml` unter `services/app/environment` ergänzen:

```
- FRAME_ANCESTORS
```

Außerdem auf `develop`-Image wechseln:

```
image: ghcr.io/solectrus/solectrus:develop
```

In `.env` die Website eintragen, in die die Einbetteung erfolgen soll, hier ein Beispiel:

```
FRAME_ANCESTORS=https://iframetester.com
````

Dann Container neu starten.

Das Ergebnis sieht dann so aus:
https://iframetester.com/?url=https://solectrus.ledermann.dev

**Comment by Gabinger** [comment]
Sehr gut, vielen Dank!!!

**Comment by BarnyXX** [comment]
Top! Vielen Dank!

**Comment by Gabinger** [comment]
> Top! Vielen Dank!

Hey, hast du es hinbekommen in einer VIS?? Ich bekomme es nicht hin :(

**Comment by ledermann** [comment]
@Gabinger Was genau hast Du probiert und was genau ist das Ergebnis?

**Comment by Gabinger** [comment]
Hi,
ich habe auf einer Seite http://192.168.0.85:8082/vis/index.html?main#Wetter_temp ein iframe eingebaut.
Quelle für den Inhalt des Iframes ist http://192.168.0.85:3000/inverter_power/now
In der .env habe ich FRAME_ANCESTORS=http://192.168.0.85:8082/vis/index.html?main#Wetter_temp ergänzt, in der docker-compose.yml habe ich -FRAME_ANCESTORS eingetragen.
Ergebnis: Verbindung verweigert :(

![image](https://github.com/solectrus/solectrus/assets/113509789/398f35c6-ffc5-4619-9f8c-013cd60c534f)
![image](https://github.com/solectrus/solectrus/assets/113509789/1f272fd6-7cef-48ee-ae72-75b50f0287b8)
![image](https://github.com/solectrus/solectrus/assets/113509789/877e4b28-73af-40f9-8a9f-0590104e21cc)

**Comment by ledermann** [comment]
Die Sperre basiert auf der Content-Security-Policy, siehe hier:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors#syntax

Versuch es mal ohne Pfadangabe, also so:

```
FRAME_ANCESTORS=http://192.168.0.85:8082
```

Ansonsten bitte mal prüfen, ob die Einstellung wirklich aktiv ist. Im Browser, Developer Tools, hier am Beispiel meiner Live-Demo, der Pfeil zeigt an die Stelle, wo der Inhalt der Variable stehen muss:
![CleanShot 2024-01-09 at 12 21 58@2x](https://github.com/solectrus/solectrus/assets/3557/f33c9805-d66e-4073-90be-54a3b8feac94)

Wenn auch das nicht weiterhilft: Versuche mal, falls möglich, statt der IP-Adresse eine (lokale) Domain zu verwenden. Also so, dass SOLECTRUS z.B. unter `solectrus.lan` erreichbar ist.

**Comment by Gabinger** [comment]
Scheint nicht aktiv zu sein.....
![image](https://github.com/solectrus/solectrus/assets/113509789/96f292bd-be6c-4e23-87f2-9a48d9459c29)

**Comment by ledermann** [comment]
Hm, prüfe es bitte nur mit SOLECTRUS, also rufe http://192.168.0.85:3000 auf und schaue Dir die Header des ersten Requests an. Wenn da wirklich `frame-ancestors 'none'` steht, dann liegt es allein an der ENV-Variable `FRAME_ANCESTORS`. Bitte prüfen:

1. Steht die Variable wirklich richtig in der `.env`?
2. Steht die Variable wirklich richtig in der `docker-compose.yml` unter `services.app.environment`?
3. Hast den ganzen Stack wirklich neu gestartet, also mit `docker-compose down`und `docker-compose up`?
4. Hast Du wirklich Version `v0.14.0` oder neuer?

**Comment by BarnyXX** [comment]
Ich habe bei mir folgendes eingetragen:
FRAME_ANCESTORS=*
Weil ich teilweise auch ioBroker selbst in einem iFrame laufen habe.

**Comment by Gabinger** [comment]
> Hm, prüfe es bitte nur mit SOLECTRUS, also rufe http://192.168.0.85:3000 auf und schaue Dir die Header des ersten Requests an. Wenn da wirklich `frame-ancestors 'none'` steht, dann liegt es allein an der ENV-Variable `FRAME_ANCESTORS`. Bitte prüfen:
Den Eintrag wie auf deinem Bild sehe ich nicht......

![image](https://github.com/solectrus/solectrus/assets/113509789/9b553368-24c0-48dd-af07-5b3e0bc1e024)

> 1. Steht die Variable wirklich richtig in der `.env`?
Ja denke schon..... Habe es einfach unten drunter geschrieben, jetzt mit *
![image](https://github.com/solectrus/solectrus/assets/113509789/05f27c04-901a-4818-991f-a3f150bf8cc9)

> 2. Steht die Variable wirklich richtig in der `docker-compose.yml` unter `services.app.environment`?
Ja....
![image](https://github.com/solectrus/solectrus/assets/113509789/9f10e340-c85b-4b8f-9ab7-3ff88beac49a)

> 3. Hast den ganzen Stack wirklich neu gestartet, also mit `docker-compose down`und `docker-compose up`?
Ohne die - dazwischen aber: Ja

> 4. Hast Du wirklich Version `v0.14.0` oder neuer? 
0.14.2

**Comment by Gabinger** [comment]
Warum auch immer aber jetzt geht es !!!! Habe nochmal alles neu gestartet, den IFrame nochmal neu eingebunden.
Danke euch!!!!!!!!!!!!

**Comment by ledermann** [comment]
Alles klar, freut mich, dass es nun funktioniert 😄

**Comment by Gabinger** [comment]
> Alles klar, freut mich, dass es nun funktioniert 😄

Ja mal wieder ne schwere Geburt :).... Danke nochmal!
