### ISSUE TITLE
Vergangene Werte

### ISSUE THREAD

**Issue by Deanw1975** [solectrus/solectrus#2497]
Hallo zusammen,

ich musste Solectrus neu aufsetzen.
Hatte in der .env zuerst ein falsches Datum eingetragen :( und dann den csv-importer gestartet.

Nachdem ich meinen Fehler gemerkt hatte, habe ich den Importer neu laufen lassen.
Dennoch werden mir unter den TOP 10 die Vergangenen Werte nicht dargestellt, nur die Werte seit der Installation.

![image](https://github.com/solectrus/solectrus/assets/108386811/820845f8-2688-4aa3-aa6f-d66de0e3179e)

Wenn ich mir unter "Verlauf" das Jahr ansehe, werden die Werte des Jahres 2023 dargestellt.
![image](https://github.com/solectrus/solectrus/assets/108386811/709f4988-24bb-4053-bcec-830d7b033037)

Ich komme aber nicht auf die Werte aus 2022, der Pfeil ist ausgeblendet um weiter zurück zu gehen.
![image](https://github.com/solectrus/solectrus/assets/108386811/6f3e83d1-5abe-4609-a7cb-8f0f02e0516a)

Die Anlage wurde im April 2022 installiert.

Auch kann ich in der Wochen- oder Monatsansicht kann ich nur bis zur Installation von Solectrus zurück (30.10.2023):

![image](https://github.com/solectrus/solectrus/assets/108386811/04622eb3-bcc1-4cbd-a6f0-0d68c4d01e58)

![image](https://github.com/solectrus/solectrus/assets/108386811/72e23378-0ccb-4e6a-9377-409730ce98d9)

![image](https://github.com/solectrus/solectrus/assets/108386811/49c6d098-a29e-4e1f-8c34-f99abc3cbcf2)

In der letzten Ansicht sieht man, dass die Daten aus dem Oktober da sind.

Was kann ich tun?

VG
Dean

**Comment by ledermann** [comment]
Bitte folgende zwei Dingen prüfen:

- Wenn die `.env`-Datei geändert wurde, müssen danach unbedingt die Container neu gestartet werden, um die Änderung zu übernehmen. Also `docker compose restart` ausführen.
- Nach einem Import von Daten muss der Redis-Cache geleert werden: `docker exec -it solectrus-redis-1 redis-cli FLUSHALL`. Näheres dazu hier: https://github.com/solectrus/csv-importer#beware-of-caching-issues

Ein falsches `INSTALLATION_DATE` in der `.env` hat übrigens keine Auswirkungen auf den Importer, sondern nur auf das Dashboard selbst.

**Comment by Deanw1975** [comment]
Servus, beides schon gemacht.
Gerade nach deiner Anweisung wiederholt. Kein Erfolg

**Comment by ledermann** [comment]
Was genau steht denn in `INSTALLATION_DATE` der `.env`? Da muss das Datum der Installation der PV-Anlage stehen (also in Deinem Fall aus April 2022), also nicht etwas das Datum der Installation von SOLECTRUS.

Wurden die Container wirklich neu gestartet? Es gab schon mal den Fall, dass ein Restart wegen irgendwelcher Fehler fehlgeschlagen ist und somit der alte Container weitergelaufen ist. Finden sich irgendwelche Fehlermeldungen in den Logs?

Falls auch das nicht hilft, poste bitte mal die `.env`, die `docker-compose.yml` und den Output von `docker ps`.

**Comment by Deanw1975** [comment]
Nachdem ich deine Anweisung durch bin, hatte ich auch einen Reboot durchgeführt.

Hier die gewünschten Infos

docker ps
CONTAINER ID   IMAGE                                         COMMAND                  CREATED      STATUS                    PORTS                                                                                            NAMES
ee6b0a902555   ghcr.io/solectrus/solectrus:latest            "docker/startup.sh"      3 days ago   Up 11 minutes (healthy)   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                        solectrus-app-1
d2ce3ecd83d1   ghcr.io/solectrus/mqtt-collector:latest       "/bin/sh -c 'bundle …"   3 days ago   Up 11 minutes                                                                                                              solectrus-mqtt-collector-1
6071ea6d45fb   ghcr.io/solectrus/forecast-collector:latest   "/bin/sh -c 'bundle …"   3 days ago   Up 10 minutes                                                                                                              solectrus-forecast-collector-1
b6c0229bb3c9   influxdb:2.7-alpine                           "/entrypoint.sh infl…"   3 days ago   Up 11 minutes (healthy)   8086/tcp                                                                                         solectrus-influxdb-1
dd9f88cc51b6   redis:7-alpine                                "docker-entrypoint.s…"   3 days ago   Up 11 minutes (healthy)   6379/tcp                                                                                         solectrus-redis-1
1c86239974e4   postgres:16-alpine                            "docker-entrypoint.s…"   3 days ago   Up 11 minutes (healthy)   5432/tcp                                                                                         solectrus-db-1
8217712f2de3   containrrr/watchtower                         "/watchtower --scope…"   3 days ago   Up 11 minutes (healthy)   8080/tcp                                                                                         solectrus-watchtower-1
d94625da18b7   portainer/portainer-ce:latest                 "/portainer"             3 days ago   Up 3 days                 0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 0.0.0.0:9443->9443/tcp, :::9443->9443/tcp, 9000/tcp   portainer

############################################################

.env

#######################################
# Dashboard application (the main part)
#
# Domain name or IP address of your host
APP_HOST=solectrus.local
#
# SSL redirect: Use "true" (which is the default) if you want to auto-redirect to https
FORCE_SSL=false
#
# Secret token to secure cookies, 128 chars long hexadecimal encoded string (don't use this example, make some random changes!)
# Currently there are no cookies in Soletrus, but this may change in the future
xxxxxxxxxxxxxxxxxxxxxxxxx
#
# Date of commissioning of your photovoltaic system
INSTALLATION_DATE=2022-04-12
#
# Price you pay for 1kWH (in EUR)
# Can be changed later in the UI when logged in as administrator
ELECTRICITY_PRICE=0.31
#
# Price you get for 1kWH (in EUR)
# Can be changed later in the UI when logged in as administrator
FEED_IN_TARIFF=0.0777
#
# Password for the PostgreSQL database, used by the app to comunicate internally with the database
POSTGRES_PASSWORD=xxxxxxxxx
#
# Password to login as administrator, required to manage settings like historical prices
ADMIN_PASSWORD=xxxxxxxxx

##################################################################
# Influx database settings
#
# Influx host (to access from SOLECTRUS dashboard and collectors)
INFLUX_HOST=influxdb
INFLUX_SCHEMA=http
INFLUX_PORT=8086
#
# Credentials for the Influx database, don't change after the first run!
INFLUX_ORG=solectrus
INFLUX_USERNAME=xxxxxxxxx
INFLUX_PASSWORD=xxxxxxxxx
INFLUX_ADMIN_TOKEN=xxxxxxxxx
#
# Set these names before first run, they can't be changed later!
INFLUX_BUCKET=my-solectrus-bucket
INFLUX_MEASUREMENT_PV=xxxxxxxxx
INFLUX_MEASUREMENT_FORECAST=Forecast
#
# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, you can use two separate tokens, created via the InfluxDB frontend.
InfluxDB frontend.
INFLUX_TOKEN_WRITE=my-super-secret-admin-token
INFLUX_TOKEN_READ=my-super-secret-admin-token
#
# Volume path for storing the Influx data
INFLUX_VOLUME_PATH=/home/pi/solectrus/influxdb
#
# Interval in seconds for polling the InfluxDB
INFLUX_POLL_INTERVAL=5

##################################################################
# REDIS settings
#
REDIS_VOLUME_PATH=/home/pi/solectrus/redis

##################################################################
# PostgreSQL database settings
#
DB_VOLUME_PATH=/home/pi/solectrus/postgresql

##################################################################
# MQTT Collector

# MQTT Broker credentials
MQTT_HOST=192.168.178.xxxxxxxxx
MQTT_PORT=1884
#MQTT_SSL=true
MQTT_USERNAME=xxxxxxxxx
MQTT_PASSWORD=xxxxxxxxx

# MQTT topics
# https://docs.evcc.io/docs/reference/api#mqtt-api
MQTT_TOPIC_HOUSE_POW=evcc/site/homePower
MQTT_TOPIC_GRID_POW=evcc/site/gridPower
MQTT_TOPIC_BAT_FUEL_CHARGE=evcc/site/batterySoc
MQTT_TOPIC_BAT_POWER=evcc/site/batteryPower
MQTT_TOPIC_INVERTER_POWER=evcc/site/pvPower
MQTT_TOPIC_WALLBOX_CHARGE_POWER=evcc/loadpoints/1/chargePower

# MQTT options
MQTT_FLIP_BAT_POWER=true

##################################################################
# Solar forecasting with https://forecast.solar
# API docs: https://doc.forecast.solar/doku.php?id=api:estimate
#
# Latitude of the plant location


##################################################################
# Solar forecasting with https://forecast.solar
# API docs: https://doc.forecast.solar/doku.php?id=api:estimate
#
# Latitude of the plant location
FORECAST_LATITUDE=48.5543
#
# Longitude of the plant location
FORECAST_LONGITUDE=12.1602
#
# Plane declination: 0 (horizontal) - 90 (vertical)
FORECAST_DECLINATION=8
#
# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
FORECAST_AZIMUTH=-90
#
# Installed modules power in kilowatt peak (kWp)
FORECAST_KWP=9.75
#
# Optional damping factors (http://doc.forecast.solar/damping)
# FORECAST_DAMPING_MORNING=0.5
# FORECAST_DAMPING_EVENING=0
#
# Optional configuration for multiple planes
#
# Number of planes
# FORECAST_CONFIGURATIONS=2
#
# Starting from 0, add params different from the values defined above
# FORECAST_0_AZIMUTH=90
# FORECAST_0_KWP=5.32
# FORECAST_1_AZIMUTH=-90
# FORECAST_1_KWP=7.84
#
# Available params are:
# - FORECAST_x_LATITUDE
# - FORECAST_x_LONGITUDE
# - FORECAST_x_DECLINATION
# - FORECAST_x_AZIMUTH
# - FORECAST_x_KWP
# - FORECAST_x_DAMPING_MORNING
# - FORECAST_x_DAMPING_EVENING
#
# Update interval in seconds, 900s = 15 minutes, the public (and free) API allows a minimum of 900 seconds
# BEWARE: Each plane counts as one request, so if you have multiple planes, you need to multiply the interval!
FORECAST_INTERVAL=900

#####################################################################

docker.compose.yml

version: '3.7'

services:
  app:
    image: ghcr.io/solectrus/solectrus:latest
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    depends_on:
      db:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - db
      - influxdb
      - redis
    ports:
      - 3000:3000
    environment:
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - INSTALLATION_DATE
      - ELECTRICITY_PRICE
      - FEED_IN_TARIFF
      - ADMIN_PASSWORD
      - DB_HOST=db
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379/1
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT_PV
      - INFLUX_MEASUREMENT_FORECAST
      - INFLUX_POLL_INTERVAL
    healthcheck:
      test: ['CMD-SHELL', 'nc -z 127.0.0.1 3000 || exit 1']
    restart: always

  influxdb:
    image: influxdb:2.7-alpine
    labels:
      - 'com.centurylinklabs.watchtower.scope=solectrus'
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup

**Comment by ledermann** [comment]
Hm, das sieht alles korrekt aus. 

Was mir noch einfällt: Check mal die Strompreise und die Einspeisevergütung. Decken beide wirklich den ganzen Zeitraum seit Installation der Anlage ab? Der älteste Preis muss ein Gültigkeitsdatum vom 2022-04-12 oder früher haben.

**Comment by ledermann** [comment]
Nochmal zum Redis-Löschen: Hat das wirklich geklappt oder gab es dabei möglicherweise eine Fehlermeldung? Es müsste so aussehen:

```
pi@raspberrypi:~/solectrus $ docker exec -it solectrus-redis-1 redis-cli FLUSHALL
OK
```

Wichtig ist das `OK` als Rückmeldung.

Ansonsten: Ich sehe, dass Du Portainer verwendest. Hast Du da vielleicht einen Stack für SOLECTRUS angelegt, der mit ganz anderen Umgebungsvariablen arbeitet? Um das zu klären: Bitte prüfe, um folgendes Statement das korrekte `INSTALLATION_DATE` ausgibt:

```
docker exec -it solectrus-app-1 env
```

Wenn das alles auch nichts bringt: Stellt sich das Problem immer noch genauso dar wie oben beschrieben, also inklusive des Problems, dass man nicht zurück ins Jahr 2022 navigieren kann? 

Tut mir leid, dass es so mühsam ist. Ich denke, hier müsste langfristig eine Funktion in SOLECTRUS integriert werden, die die Korrektheit der Installation prüft und ggfs. Hinweise auf Korrekturansätze ausgibt.

**Comment by Deanw1975** [comment]
Servus, 
mit dem folgenden Befehl wird das falsche Datum ausgegeben:

docker exec -it solectrus-app-1 env

Hier kommt: INSTALLATION_DATE=2023-10-30

Auch der falsche Preis bei 
ELECTRICITY_PRICE=0.31

in der .env steht es aber richtig
Wie behebe ich das nun?

VG
Dean

**Comment by ledermann** [comment]
Wir scheinen der Sache auf die Spur zu kommen. Deine Änderungen in der .env werden also gar nicht berücksichtigt. Damit meine ich `INSTALLATION_DATE`, die Variable `ELICTRICITY_PRICE` hingegen wird nur beim ersten Start verwendet und kann dann in SOLECTRUS (bei den Strompreisen) geändert werden.

Bitte stelle sicher, dass sich `.env` und `docker-compose.yml` im gleichen Ordner befinden und du dich auch in diesem Ordner befindest, wenn du `docker-compose up` eingibst. Bitte stelle außerdem sicher, dass die Datei auch wirklich `.env` heißt, also inklusive Punkt.

Solltest du Portainer benutzen, kann die ganze Sache anders aussehen. Dort werden Umgebungsvariablen in der UI verwaltet, d.h. die `.env`-Datei wird gar nicht benutzt.

**Comment by Deanw1975** [comment]
Das war es fast;-)

Nicht docker-compose up hat geholfen sondern
docker compose up

DANKE! für die Geduld

**Comment by ledermann** [comment]
Ok, je nach Docker-Version heißt es `docker-compose up` oder `docker compose up`. Mal mit, mal ohne Bindestrich. Letzteres ist in neueren Versionen der Fall.

Weiter oben hatte ich aber selbst etwas Falsches erzählt: `docker coompose restart` hilft **nicht**, weil das nur die bestehenden Container neu startet, aber sie nicht neu erstellt. Somit werden auch keine geänderten Umgebungsvariablen übernommen. Es muss also zwingend `docker compose up` sein.

Freut mich, dass das Problem nun behoben ist.
