### ISSUE TITLE
Feature Request: HTML Meta-Tag: robots -> noindex, nofollow, noarchive hinzufügen

### ISSUE THREAD

**Issue by Marlight** [solectrus/solectrus#2687]
Moin,

tolles Tool, damit ich das für mich auch nach außen schalten kann, wäre es schön wenn man noch das meta-Tag "robots" mit `noindex, nofollow, noarchive` hinzufügen könnte. Von mir aus auch über die .env aktivierbar.

LG

**Comment by ledermann** [comment]
Ja, guter Hinweis. Das stammte noch aus Zeiten, als SOLECTRUS noch keine [separate Website](https://solectrus.de/) hatte und nur von mir selbst betrieben wurde.

Ich habe alle SEO-Geschichten jetzt herausgenommen und das `robots` meta-Tag ergänzt. Ohne `.env`-Konfiguration, es gilt also immer. Und eine `robots.txt` mit `Disallow: /` gibt es auch.

Verfügbar mit dem nächsten regulären Update. Oder für Wagemutige bereits jetzt im [develop-Image](https://github.com/solectrus/solectrus/pkgs/container/solectrus?tag=develop).
