### ISSUE TITLE
Mobile: Untere Navigation weniger eng gestalten

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#2796]
Per E-Mail erhalten:

Mit dem iPhone kollidiert die Navigation unten mit der systemweiten Funktion für das Fenster (swipen der offenen Fenster, verkleinern, Einhandbedienung). Könnte man hier etwas mehr margin-bottom geben?

**Comment by StevieC121176** [comment]
Wäre es möglich die Beschriftung der Buttons mittig zu gestalten? 

![IMG_2356](https://github.com/solectrus/solectrus/assets/113791299/606a1d87-2b68-4fd3-ba4b-330a6b7c7494)

**Comment by ledermann** [comment]
@StevieC121176 Von welchem iOS/iPhone stammt der Screenshot? Bei mir (mit iOS 17.3.1 auf iPhone 15 Pro Max) sieht es anders (und besser) aus, die Homebar integriert sich da ins UI der App, steht also nicht darunter. Daher habe ich nur den unteren Rand vergrößert.

![solectrus-ios-margin](https://github.com/solectrus/solectrus/assets/3557/d8083edf-cc54-4ce5-b540-50bed51ae16e)

**Comment by StevieC121176** [comment]
Den Screenshot hatte ich vorhin mit meinem iPhone 15pro erstellt mit ios17.4 . Ich fürchte das das kein Bug von Apple ist, sondern so gewollt (keine Progressive Darstellung mehr). Ich denke dadurch wirkt das so bescheiden.
Leider wird man irgendwann gezwungen sein auf ios17.4 oder höher zu wechseln.
