### ISSUE TITLE
Tooltip mit live Werte

### ISSUE THREAD

**Issue by novodrom** [solectrus/solectrus#2809]
Finde es toll, dass die Balken unter AKTUELL sich den Live Daten anpassen und in der Höhe / prozentual verändern.

Um nicht in den Charts die geraden aktuellen Werte herauszusuchen, fände ich es eine tolle Möglichkeit, durch langes drücken (Mobile) oder hovern auf den jeweiligen Balken, diese in den Tooltip’s zu sehen.

Die zeigen momentan den letzten Wert seit dem Reload der Seite an.

**Comment by novodrom** [comment]
Sehe gerade, das wurde schon als Bug registriert #1886

**Comment by ledermann** [comment]
Ja, korrekt, das ist ein bekannter Bug. Aus noch ungeklärten Gründen werden die Tooltips nicht aktualisiert. Werde ich weiter in #1886 behandeln.
