### ISSUE TITLE
Kein Vollbild mehr unter iOS 17.4 ?

### ISSUE THREAD

**Issue by StevieC121176** [solectrus/solectrus#2814]
Ich weiß jetzt nicht ob es durch die aktualisierte Solectrus oder iOS Version auftritt, aber bei mir wird Solectrus durch öffnen auf dem homescreen nicht mehr als vollbild angezeigt. Zur Verdeutlichung hier mal 2 Screenshots:

![IMG_2351](https://github.com/solectrus/solectrus/assets/113791299/accd1701-1b18-41c3-aca8-2a4069b0299c)
![IMG_1282](https://github.com/solectrus/solectrus/assets/113791299/5c6bfd55-7b14-4f89-be85-9529ceb4c06c)

**Comment by ledermann** [comment]
Welches iOS? Ich habe genau von diesem Phänomen gehört, das unter 17.4-beta auftritt. Auf meinem 17.3.1 ist alles ok.

**Comment by StevieC121176** [comment]
Ja ich nutze 17.4 Beta.

_In der EU sind sogenannte „progressive Web-Apps“ unter iOS 17.4 nicht mehr progressiv.

**Comment by ledermann** [comment]
Mal abwarten, wie sich das so entwickelt. Derzeitig herrscht [große Aufregung](https://stadt-bremerhaven.de/ios-17-4-unterstuetzung-fuer-web-apps-pwa-anscheinend-eingestellt/) über die anstehenden Änderungen Apples für den EU-Raum. Möglicherweise sind aber auch noch Bugs im Spiel.

Das Problem beschränkt sich nicht auf SOLECTRUS, sondern betrifft grundsätzlich alle Websites, die als App "installiert" werden. Ich verfolge das mit Sorge, da ich PWAs für eine ziemlich feine Sache halte.

**Comment by ledermann** [comment]
Nix Neues zum Thema, aber gute Zusammenfassung der Situation:
https://www.heise.de/news/Web-Apps-ausser-Funktion-iOS-17-4-Beta-bereitet-Entwicklern-grosse-Sorge-9627974.html

**Comment by StevieC121176** [comment]
echt grauenvoll was die da veranstalten...
zumindest gibt es eine Möglichkeit wenigstens den Look&Feel wieder herzustellen. Nach dem öffnen in der Adresszeile auf das"aA" klicken und dann Symbolleiste ausblenden wählen. 
Leider muss man das nach jedem öffnen erneut machen.

![IMG_2361](https://github.com/solectrus/solectrus/assets/113791299/9e2f570d-1f9a-4c60-b676-b9b4b486d599)
![IMG_2362](https://github.com/solectrus/solectrus/assets/113791299/c4caa2be-61aa-4272-b962-06b3f4725e52)

**Comment by Timokirch** [comment]
https://developer.apple.com/support/dma-and-apps-in-the-eu/

**Comment by spirit0607** [comment]
Betrifft das alle Browser in iOS 17.4? Oder nur Safari? Mit Edge z.B. funktioniert Vollbild ja auch.

**Comment by StevieC121176** [comment]
Apple ist zurück gerudert. Mit dem heutigen iOS 17.4 funktionieren PWAs wieder.
