### ISSUE TITLE
Anzeige Einspeisung immer mit Icon „!“

### ISSUE THREAD

**Issue by StevieC121176** [solectrus/solectrus#2841]
Bei mir wird neuerdings die Einspeisung immer mit einem Icon „!“ versehen. Im Tooltip steht Begrenzung 0%. Bei mir ist aber keinerlei Begrenzung eingestellt da es bei der Inbetriebnahme meiner Anlage die 70% Regel nicht mehr gab.

![IMG_2422](https://github.com/solectrus/solectrus/assets/113791299/8f8dafa9-2a6d-46d0-91b8-de19cc7ffd6a)

![IMG_2423](https://github.com/solectrus/solectrus/assets/113791299/7e230b03-b2ba-4175-bd1a-c5ce71743f2a)

**Comment by hambue** [comment]
Schau mal in den Logs der letzten Tage, ob es da infolge eines NPU-Fehlers zu einer externen Steuerung kam. Manchmal bleiben da komische Werte wie eine Einspeisebegrenzung von 1W stehen und verschwinden erst wieder nach einem Neustart des Speichers. Der genaue Eintrag in den Logs lautet dann `External Charge Control`.

**Comment by ledermann** [comment]
Ich denke, bei @StevieC121176 ist gar kein SENEC im Einsatz, daher muss er sich auch nicht mit NPU-Fehlern herumplagen ;-)

Der SENEC-Collector schreibt ins Feld `power_ratio` der InfluxDB die mögliche Einspeisebegrenzung rein. Typische Werte sind 70 oder 100. Der MQTT-Collector kann das in der aktuellen Version noch nicht, d.h. bei Verwendung des MQTT-Collectors gibt es diesen Wert nicht in InfluxDB.

Und jetzt entsteht der Fehler: SOLECTRUS interpretiert seit Version `0.14.2` diesen fehlenden Wert als 0 und stellt ihn dar. Ist natürlich Blödsinn. Ich korrigiere das.

**Comment by ledermann** [comment]
Fixed in `develop`. @StevieC121176 Passt es so?

**Comment by StevieC121176** [comment]
Scheint zu funktionieren, das ! Icon ist bis jetzt nicht wieder aufgetaucht.

![IMG_2427](https://github.com/solectrus/solectrus/assets/113791299/cc718937-3348-47e5-be45-b01f44b134f3)

**Comment by ledermann** [comment]
@StevieC121176 Prima, danke für die Rückmeldung!
