### ISSUE TITLE
Größe der Icons bei geringer Höhe der Anzeigefelder

### ISSUE THREAD

**Issue by StevieC121176** [solectrus/solectrus#2884]
Die Icons werden bei abnehmender Höhe der Anzeigefelder teilweise zu groß dargestellt bzw. sogar verdeckt 

![IMG_2514](https://github.com/solectrus/solectrus/assets/113791299/dd29978b-0552-4917-83c0-3b846c3919ed)
![IMG_2513](https://github.com/solectrus/solectrus/assets/113791299/bd2d0f57-56b2-4495-929b-bf6b3e923daf)
![IMG_2506](https://github.com/solectrus/solectrus/assets/113791299/b58807b9-516d-4014-8666-4aab1ed79277)

**Comment by ledermann** [comment]
Hm, offensichtlich ein Fehler. Welche Version? Ich nehme an, die aktuelle Betaversion https://github.com/solectrus/solectrus/pull/2836.

Ist dir das vorher schon mal begegnet? Tritt das auch mit `develop` auf?

Hintergrundinfo: SOLECTRUS ermittelt einen Peak der Werte aus den letzten 30 Tagen und benutzt das für die Skalierung von Icons. Möglicherweise stimmt etwas mit der Peak-Ermittlung nicht.

In dem Zusammenhang noch folgender Hinweis: Du hast ja in den letzten Tage die Datenbank mehrfach neu aufgesetzt. Es ist ja so, dass InfluxDB-Abfragen in einem Redis-Cache liegen. Möglicherweise passt der Cache nicht zum Stand der InfluxDB. Daher einfach mal den Cache löschen und gucken, ob das Auswirkungen hat:

```
docker exec -it solectrus-redis-1 redis-cli FLUSHALL
```

**Comment by StevieC121176** [comment]
Ja die aktuelle Beta #2836 
Tritt aber auch mit der develop Version auf.
Aber es ist mir tatsächlich erst in den letzten Tagen aufgefallen. Ich dachte erst an ein Feature bis ich heute gesehen hatte das das Icon abgeschnitten wird.

`docker exec -it solectrus-redis-1 redis-cli FLUSHALL`

hat geholfen. Die Icon sind wieder normal groß

![IMG_2515](https://github.com/solectrus/solectrus/assets/113791299/47282942-b105-4843-8458-5436e77e6e39)

**Comment by ledermann** [comment]
Ok, dann waren also im Cache noch Daten, die nicht zur neu aufgesetzten InfluxDB passten. Somit alles geklärt, nichts weiter zu tun.
