### ISSUE TITLE
Responsive Layout für große Hochformat-Displays

### ISSUE THREAD

**Issue by StevieC121176** [solectrus/solectrus#3042]
Wäre es möglich den Fulscreen Modus von Solectrus auch an Hochformat Screens anzupassen?
Als Beispiel kann ich hier EVCC anführen, wo das gerade umgesetzt wurde und sehr gut funktioniert.
sh hier: https://github.com/evcc-io/evcc/pull/13508

hier mal ein Beispielbild Vor und Nachher

vorher:
![IMG_2798-1](https://github.com/solectrus/solectrus/assets/113791299/4f4a1a1d-ebd8-498e-b75b-f2d657414893)

nachher:
![IMG_2816](https://github.com/solectrus/solectrus/assets/113791299/810b61af-7050-4f62-8040-b9783939b95f)

**Comment by ledermann** [comment]
Du beziehst dich auf das Phänomen, was du [in #2511 beschrieben](https://github.com/solectrus/solectrus/issues/2511#issuecomment-2052028943) hattest, oder?

> die normale Kachelansicht wird korrekt dargestellt sh. Foto. Ich kann auch den vollbildmodus in SOLECTRUS aktivieren, nur da wird leider in das Querformat gewechselt und somit bleibt die untere Bildschirmhälfte leer. Das Display im Kühlschrank ist senkrecht.

> evtl. liegt es an der Auflösung. normal im Hochformat werden 982x1514 Pixel genutzt, beim Fullscreen dann 1080x1920px

Ich hatte das ursprünglich nicht verstanden und vermutet, dass es ein Problem mit dem Fullscreen-Mode bzw. dem Ausblenden des Browser UI ist. Das ist es aber gar nicht, es ist eine reine Frage der Breakpoints für das responsive Layout.

Es sieht bei dir also offenbar so aus:

| 986x1514 (OK)     | 1080x1920  (falsch) |
| ------------- | ------------- |
| ![normal](https://github.com/solectrus/solectrus/assets/3557/bd9e56f2-1b71-45d2-881a-255e212e51fb) | ![Fullscreen](https://github.com/solectrus/solectrus/assets/3557/9975153d-ce11-4e14-8ff0-0f7097806801)  |

Danke für den weiteren Hinweis, das lässt sich beheben, ich kümmere mich darum.

**Comment by ledermann** [comment]
@StevieC121176: Ich habe das nun korrigiert, d.h. die Darstellung auf großen und gleichzeitig hohen Displays (also wie bei deinem Kühlschrank) erfolgt jetzt etwas anders. Die Änderung ist in den Branches `develop`, `separate_consumer` und `next`. Bin gespannt, ob es bei dir nun passt.

**Comment by StevieC121176** [comment]
Sobald ich heute Abend wieder zu Hause bin Probier ich es gleich aus. Vielen Dank

**Comment by StevieC121176** [comment]
@ledermann funktioniert perfekt, danke 

![IMG_2825](https://github.com/solectrus/solectrus/assets/113791299/54ebed72-46e0-4f5f-9578-fb242aeb9d32)
