### ISSUE TITLE
Chart für E-Auto wird nach Ladeende nicht weitergezeichnet

### ISSUE THREAD

**Issue by gereons** [solectrus/solectrus#3130]
Ist mir gestern im "next"-Branch aufgefallen: Aktuell-Ansicht steht auf E-Auto, während des Ladens war alles OK. Der Chart rechts wurde aber nach Ladeende nicht weitergezeichnet (weil nur noch 0-Werte nachkommen?), die Anzeige links wurde korrekt aktualisiert.

Evtl gibt's einen Zusammenhang mit #3032?

**Comment by ledermann** [comment]
Gut beobachtet, danke für den Hinweis. Es liegt tatsächlich an den 0-Werten und ist jetzt korrigiert (in `develop`).

Die Docker-Tags `next` und `develop` zeigen derzeitig übrigens das gleiche Image.

**Comment by gereons** [comment]
Danke für den (wieder mal!) super schnellen Fix 👍
