### ISSUE TITLE
Buttons unten verschwinden 

### ISSUE THREAD

**Issue by halmich** [solectrus/solectrus#3220]
Wenn ich unten auf Tag oder Woche klicken, verschwindet beim Smartphone die komplette Leiste. Dies tritt beispielsweise auch bei deiner Instanz auf.
Grüße Michael 
![Screenshot_20240625_200448_Opera](https://github.com/solectrus/solectrus/assets/136233344/3274c216-b380-408e-b46d-d971acfe342c)

**Comment by ledermann** [comment]
Scheint ein Seiteneffekt von #3214 zu sein. Android habe ich gerade nicht da. Habe daher einen Bugfix im Blindflug gemacht, siehe `develop`, kannst du es bitte nochmal ausprobieren?

**Comment by halmich** [comment]
Meine Instanz ist nun im Develop Mode - es geht dennoch nicht.
Deine Instanz ebenfalls weiterhin nicht.

**Comment by ledermann** [comment]
@halmich Seltsam. Was passiert denn, wenn SOLECTRUS als Icon installiert wird und Fullscreen läuft (über die Funktion "Zum Startbildschirm hinzufügen"). Gibt es da auch Probleme?

Und ist das wirklich erst seit kurzem so? Funktioniert also die Version 0.14.5 korrekt?

Kann das Problem noch jemand anderes mit Android bestätigen?

**Comment by Zeppelin-PV** [comment]
auf meinem Android Smartphone ist alles ok
ich habe allerding nur die drei Grundfunktionen in Bodenleiste, also einzeilig
@halmich hat mehrere Buttons, die Leiste ist zweizeilig, 
ob das was ausmacht ?

**Comment by halmich** [comment]
Wenn es als icon gestartet im vollbild läuft, dann bleiben die Buttons da.
@Zeppelin-PV
geh mal mit Opera oder dem samsung Browser auf https://demo.solectrus.de/inverter_power/now und klicke dann auf "Tag".
mit Chrome funktioniert es.

**Comment by ledermann** [comment]
@Zeppelin-PV Danke für dein Feedback, das ist hilfreich. Es ist also sehr abhängig vom Browser. 

@halmich: Ist das Problem denn schon immer da gewesen (und erst jetzt aufgefallen mit Opera bzw. Samsung Browser) **oder** tritt es erst seit kurzem auf (möglicherweise seit der Swipe-Implementierung)? Mit anderen Worten: Funktioniert die stabile Version `v0.14.5` korrekt auf deinem Android?

**Comment by halmich** [comment]
erst seit kurzem, seit maximal ner Woche oder so.

**Comment by Zeppelin-PV** [comment]
hab mal kurz folgende Browser getestet
Firefox, Google Chrome funktionieren einwandfrei
Samsung Browser öffnet unten eine zweizeilige Eingabezeile mit dem Effekt, dass die Solectrus Fußzeile überdeckt wird.
Interessant ist, wenn man nach rechts swiped zu morgen oder übermorgen, bleibt die Solectrus Fußzeile stehen und wird nicht überdeckt. Genau das selbe macht auch Opera. DuckDuckgo versucht irgendwie zu skalieren und streckt/staucht das Bild in der Höhe, kommt aber zu keinem Erfolg, nicht brauchbar.
Da ich nur Firefox benutze kann ich über den Verlauf wann dies zeitlich eingetreten ist nichts sagen.
... gehe erst mal Browser löschen ;)

**Comment by Zeppelin-PV** [comment]
.../ Interessant ist, wenn man nach rechts swiped zu morgen oder übermorgen, bleibt die Solectrus Fußzeile stehen und wird nicht überdeckt.
dadurch, dass hier Herkunft und Verwendung leer sind und kleiner, passiert hier nichts

**Comment by Zeppelin-PV** [comment]
noch 'ne Anmerkung, 
durch das viele probieren ist mir noch was zu der Funktion Swipe aufgefallen, daraus resultierend eine Frage
Wenn man den Swipe im Bereich Herkunft/Verwendung macht, passiert soweit nichts, der Tag wird vor- bzw. zurückgeblättert.
Wird der Swipe im Bereich Diagramm gemacht, wird die Diagramm Info eingeblendet als ob man Werte suchen wollte.
Wenn Solectrus diesen Swipe erkennt, könnte man dieses Einblenden der Diagrammbox nicht verhindern ?

**Comment by halmich** [comment]
Eben mit dem Desktop PC gestestet.
Ich habe im Firefox Solectrus im Fenstermodus hochformat laufen lassen und das Fenster ziemlich klein gezogen (vielleicht halber Bildschirm). Klicke ich nun auf "TAG" verschwindet die Leiste ebenfalls, je nach Größe sogar komplett.

![grafik](https://github.com/solectrus/solectrus/assets/136233344/b815993f-a42f-4355-8eb1-cecdf23af5ea)
![grafik](https://github.com/solectrus/solectrus/assets/136233344/fff885ee-9560-4009-981e-7ce73e0fe32f)

**Comment by ledermann** [comment]
Ok, jetzt ist es klar - das Problem der verschwindenden Buttons hat überhaupt nichts mit dem Swipe-Feature zu tun und auch nicht mit dem verwendeten Browser, sondern schlicht mit zu wenig Platz in der Vertikalen. 

Aber warum hat es zuvor geklappt? Es ist so: Vor [zwei Wochen](https://github.com/solectrus/solectrus/commit/5a0d85144c2d715530ce333dd7379d15a957b5d5) habe ich auf den Seiten Tag/Woche/Monat/Jahr die Angabe der CO₂-Reduktion ergänzt. Dadurch wird vertikal mehr Platz in der Strombilanz benötigt, das Diagramm wird also nach unten gedrückt. Bei sehr wenig verfügbarem Platz (z.B. wenn ein Browser verwendet wird, der große eigene UI-Elemente anzeigt) wird die Buttonleiste von SOLECTRUS aus dem sichtbaren Bereich heraus geschoben und verschwindet dadurch. Bei "Aktuell" ist übrigens alles korrekt, weil dort die CO₂-Reduktion gar nicht angezeigt wird.

Somit werde ich nun eine Lösung suchen, um besser mit geringem Platz zurechtzukommen.

**Comment by halmich** [comment]
Das klingt sinnig.
Wobei ich denke, dass es bei mir mit der CO2 Reduktion schon funktioniert hat. Das Problem tritt bei mir wirklich erst seit wenigen Tagen auf.

**Comment by halmich** [comment]
Übrigens tritt das Problem auch beim Notebook auf
Firefox Browser mit Lesezeichensymbolleite:
![1](https://github.com/solectrus/solectrus/assets/136233344/82d2498b-a2cd-464d-81a3-44bdaa5d5201)
![2](https://github.com/solectrus/solectrus/assets/136233344/763db1c2-7570-4a30-af40-0520fd757421)

**Comment by ledermann** [comment]
Ja, korrekt, die Darstellung funktioniert grundsätzlich nicht gut bei geringer Fensterhöhe. Das ist unabhängig von Gerät und Browser. In deinem Firefox-Desktop-Beispiel zwingen die vier bzw. fünf Kreise die Darstellung in eine Höhe, die gar nicht gegeben ist.

Das versuche ich nun zu verbessern.

**Comment by ledermann** [comment]
Ok, die Darstellung auf kleinen Displays ist nun besser:

- Das Diagramm passt sich der verfügbaren Höhe an, auch wenn diese klein ist. Zuvor gab es versehentlich eine [Mindesthöhe von 150px](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#height).
- Die Kreise in der Mitte der Strombilanz werden nun erst ab einer Mindest-Display-Höhe von 800px gezeichnet. Darunter wird eine platzsparende Variante benutzt.
- Der Text der Strombilanz-Segmente wird unterhalb einer Display-Höhe von 800px etwas kleiner dargestellt.

Zu sehen in `develop` und somit in der [Live-Demo](https://demo.solectrus.de/inverter_power/day).

Damit funktioniert die Darstellung korrekt in den oben beschriebenen Situationen, also auf einem kleinen Smartphone sowie einem Notebook mit geringer Display-Höhe. Die Buttonleiste wird nicht mehr abgeschnitten. Kannst du das bestätigen, @halmich?

**Comment by halmich** [comment]
Perfekt, läuft einwandfrei!!

**Comment by ledermann** [comment]
OK, danke für die Rückmeldung, dann schließe ich das hier.
