### ISSUE TITLE
Tagesansicht: Wert in "Verwendung" findet sich nicht im Chart

### ISSUE THREAD

**Issue by gereons** [solectrus/solectrus#3232]
Sorry, ich schon wieder mit einer Inkonsistenz in den Charts...

Für den 28.6. sagt mir die "Verwendung", dass ich ca. 2,9 kWh in mein Auto geladen habe, aber im Chart taucht nichts davon auf:

![chart28-6](https://github.com/solectrus/solectrus/assets/2861931/f1ef642c-4624-483e-b1bc-f76b774f9dc5)

Gegen 22h am 27.6. wurde noch ein Ladevorgang gestartet, der Tag sieht so aus:

![chart27-6](https://github.com/solectrus/solectrus/assets/2861931/2fb3548e-e71f-4567-9a26-86ef9ed2bc1a)

Im Influx-Explorer sehen beide Tage zusammen so aus:

![influx](https://github.com/solectrus/solectrus/assets/2861931/1b65eea0-bfc5-4037-b30f-8f1ebe84bb64)

Hier fällt die Kurve nach der 3. Ladung um 2024-06-28-00:07:00 wieder auf 0. In den 7 Minuten können bei dem Ladestrom aber keine 2,9 kWh zusammengekommen sein...

Das scheint mir noch irgendwie mit #3203 und den Messungen über Tagesgrenzen hinweg zusammenzuhängen.

Backups meiner Influxdb stelle ich bei Bedarf gerne zur Verfügung.

**Comment by ledermann** [comment]
Danke für deine nicht nachlassende Unterstützung :)

Anhand der Beschreibung konnte ich einen Fehler beheben, der seit Version 0.11 enthalten ist und dazu führte, dass bei der Summenberechnung (also Herkunft+Verwendung) fälschlicherweise immer eine Stunde des vorherigen Zeitraums mit einbezogen wurde. Statt 24 wurden also 25 Stunden aufsummiert.

Die Korrektur ist in `develop` enthalten (ab `v0.14.5-294`). Nach Installation des Updates sollte die Darstellung des 28. Juni korrekt sein, d.h. die E-Auto-Beladung sollte dann einen sehr geringen Wert enthalten (etwa 0,1 kWh schätze ich). Sämtliche andere Zeiträume werden sich ebenfalls (geringfügig) ändern.

**Comment by gereons** [comment]
Wunderbar, mit der Version sieht's jetzt passend aus. Danke!
