### ISSUE TITLE
Diagramm-Skalierung nicht immer optimal

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#3301]
Auf der Seite AKTUELL wird der Verbrauch, der sich prinzipiell nur zwischen 0% und 100% bewegen kann, auf 150% skaliert. Das ist ungünstig und sollte korrigiert werden.

![CleanShot 2024-07-26 at 17 40 27@2x](https://github.com/user-attachments/assets/34b471c6-61fe-437f-806d-cbfb6172310d)

Gemeldet von @WolfImBusch in https://github.com/orgs/solectrus/discussions/3299

**Comment by WolfImBusch** [comment]
.. kleine Ergänzung noch ... betrifft nicht nur die Seite "AKTUELL", sondern auch "TAG"

**Comment by ledermann** [comment]
Ist jetzt korrigiert, für AKTUELL und TAG. Bei Verbrauch und Autarkie reicht das Diagramm jetzt immer von 0% bis 100%.

Zu sehen in der Live-Demo, verfügbar im nächsten regulären Update.

**Comment by WolfImBusch** [comment]
Suuuuuuuuuper! Deine Geschwindigkeit macht mir Angst! :-)
