### ISSUE TITLE
Keine Aktualisierung der Reiter "Woche", "Monat", "Jahr" für Erzeugung

### ISSUE THREAD

**Issue by StevieC121176** [solectrus/solectrus#3309]
### Description (in German or English)

Mit Watchdog wird bei mir die Version aktuell gehalten (develop) seit gestern wird bei mir die Erzeugung für den Monat nicht mehr aktualisiert und seit heute zusätzlich für Woche und Jahr nicht.
Die Heute Ansicht wird korrekt dargestellt und aktualisiert. Ich habe mal ein paar Screenshots gemacht.

![IMG_3584](https://github.com/user-attachments/assets/8bfeab50-ef46-481d-a113-df32de7d72cd)
![IMG_3585](https://github.com/user-attachments/assets/7745b642-f89c-4f3f-8b8c-03c214854826)
![IMG_3586](https://github.com/user-attachments/assets/b7205eca-88f9-4ff8-b614-b376f6224340)
![IMG_3587](https://github.com/user-attachments/assets/ac2a6823-6628-40e4-8832-73182d1fd19b)
![IMG_3588](https://github.com/user-attachments/assets/8b1227ca-d53e-4fb5-a321-42434505e45b)

### What version of SOLECTRUS are you using?

v0.15.0-71

### What machine are you running SOLECTRUS on?

Raspberry Pi 4 8GB

**Comment by StevieC121176** [comment]
Ich sehe gerade, auf demo.solectrus.de kann man das auch nachvollziehen. Ab Sonntag Abend stimmen da die Daten auch nicht mehr in der Monatsansicht und ab Montag bei den anderen Ansichten auch nicht mehr. (Außer Tagesansicht)

**Comment by ledermann** [comment]
Danke für den Hinweis. Habe kürzlich das Caching "optimiert", das hatte wohl Nebenwirkungen. Ich kümmere mich darum.

**Comment by ledermann** [comment]
Die vor zwei Tagen von mir vorgenommene fehlerhafte Verbesserung führte bei der Monatsanzeige zu einer zu langen Caching-Dauer. Ich habe das rückgängig gemacht. 

Wer die fehlerhafte Entwickler-Version zwischendurch im Einsatz hatte und das Problem immer noch beobachtet, muss den Cache löschen:

```
docker exec -it solectrus-redis-1 redis-cli FLUSHALL
```

Sorry, Leute!

**Comment by StevieC121176** [comment]
Nach Löschen des Caches funktioniert wieder alles bestens.
