### ISSUE TITLE
Werte unter 50Wh werden nicht angezeigt

### ISSUE THREAD

**Issue by bennysweb** [solectrus/solectrus#3358]
### Description (in German or English)

Sind am neuen Tag, bzw. im neuen Monat/Jahr die Werte in der Tages-/Monats-/Jahresansicht noch unter 50Wh, werden keine Werte angezeigt. 
Ansicht 00:09 Uhr:
![IMG_3237](https://github.com/user-attachments/assets/36e76d6e-4ba0-41d7-a6f0-b4e78fb7e5a2)
Ansicht 00:10 Uhr:
![IMG_3238](https://github.com/user-attachments/assets/30274825-9488-4ca4-8d0b-d72ab2605da8)

### What version of SOLECTRUS are you using?

next

### What machine are you running SOLECTRUS on?

Synology NAS

**Comment by ledermann** [comment]
Gut gesehen, danke für den Hinweis!

Das Ausblenden des Wertes war eine Altlast, die schon lange nicht mehr erforderlich ist. Ich habe das korrigiert.
