### ISSUE TITLE
100% PV-Anteil bei fehlendem Power-Splitter

### ISSUE THREAD

**Issue by Zeppelin-PV** [solectrus/solectrus#3419]
### Beschreibung (auf Deutsch oder Englisch)

mir ist folgendes aufgefallen
im Januar und Februar war unser Speicher in der Fernabschaltung, somit mise Autarkie 29% und viel Netzbezug 266kWh
habe heute den Monat Januar angeschaut und festgestellt, dass im Hausverbrauch trotzdem 100% aus PV angezeigt wird,
was eigentlich nicht sein kann
ist das Tooltip für historische Daten ungeeignet ?

![grafik](https://github.com/user-attachments/assets/6bab68e2-b1d9-4264-b2d0-e2fae4f0c4b5)

### Welche Version von SOLECTRUS verwendest du?

0.16.0

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Raspberry 4

**Comment by Zeppelin-PV** [comment]
das Tooltip fehlte
![grafik](https://github.com/user-attachments/assets/196ca904-85f8-41fc-a5e4-8178e233f433)7

**Comment by ledermann** [comment]
Du hast völlig recht, das ist ein Fehler, der unter folgenden Umständen auftritt:

- Kein Power-Splitter installiert, also in InfluxDB keine Netzbezugs-Anteile für die Verbraucher vorhanden
- Sponsoring aktiv, also Zugriff auf den Power-Splitter-Daten erlaubt

Es wird dann fälschlicherweise angenommen, dass der PV-Anteil 100 % ist, was natürlich **falsch** ist. Auch die 0 € sind verkehrt.

Der Fehler ist bereits korrigiert (in `develop`). Der PV-Anteil sowie die Kosten werden damit nur angezeigt, wenn der Power-Splitter auch aktiv ist.

**Comment by ledermann** [comment]
Korrektur steht jetzt mit Version 0.16.1 bereit.
