### ISSUE TITLE
Ergänzung Datum bei "Seit Inbetriebnahme"

### ISSUE THREAD

**Issue by spirit0607** [solectrus/solectrus#3426]
### Beschreibung (auf Deutsch oder Englisch)

Hallo Georg,

nur ein kleiner Vorschlag oder Idee: Wie wäre es auf der "Gesamt" Ansicht bei "Seit Inbetriebnahme" das tatsächliche Datum der Inbetriebnahme zu ergänzen. Dies ist ja in der .env Datei hinterlegt. Bei mir könnte es dann z.B. lauten: "Seit Inbetriebnahme am 20.06.2022"

<img width="1310" alt="Bildschirmfoto 2024-09-04 um 20 22 58" src="https://github.com/user-attachments/assets/602db237-3359-4585-a2e1-7eafe8c1dfdc">

**Comment by ledermann** [comment]
Ja, gute Idee. Ich habe das gerade ergänzt, mit einer kleinen Variation: Der Zeitraum seit Inbetriebnahme wird relativ angegeben, also z.B. "Seit Inbetriebnahme vor fast 4 Jahren". Mittels Tooltip wird dann das genaue Datum angezeigt.

[Zu sehen in der Live-Demo](https://demo.solectrus.de/inverter_power/all), wird im nächsten Update enthalten sein.

**Comment by ledermann** [comment]
Die Änderung steht jetzt mit Version 0.16.1 bereit.
