### ISSUE TITLE
Umbenennung Akku

### ISSUE THREAD

**Issue by bennysweb** [solectrus/solectrus#3556]
### Beschreibung (auf Deutsch oder Englisch)

Der besseren Übersichtlichkeit halber schlage ich vor, die Bezeichnung "Akku" in der Auswahl über den Graphen in "Hausakku" und "Ladestand Akku" in "Ladestand Hausakku" umzubenennen. 

### Welche Version von SOLECTRUS verwendest du?

17.0

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Synology

**Comment by ledermann** [comment]
Ja, guter Vorschlag, den ich gerne übernehme. Zu sehen in der Live-Demo und in `develop`.

**Comment by bennysweb** [comment]
Super, wieder mal vielen Dank für die prompte Umsetzung!
