### ISSUE TITLE
Diagramm Hausverbrauch: Split-Darstellung auch ohne Power-Splitter

### ISSUE THREAD

**Issue by ledermann** [solectrus/solectrus#3608]
Vorschlag aus #3597 von @Zeppelin-PV:

Seit Version `v0.16` wird im Diagramm zum Hausverbrauch durch den Einsatz des [Power-Splitters](https://docs.solectrus.de/referenz/power-splitter/) eine Darstellung mit gestapelten Balken genutzt. Dadurch wird sichtbar, ob der benötigte Strom aus PV (grün) oder aus dem Netz (rot) stammt:

![Split-Darstellung](https://github.com/user-attachments/assets/4afe4601-67c9-443d-894b-f63a1994e5ca)

Diese Darstellung ist auch für E-Auto und Wärmepumpe verfügbar und setzt den Power-Splitter zwingend voraus. Ohne dessen Berechnungen ist eine Split-Darstellung nicht möglich.

Nun gibt es aber den Fall, dass ein Nutzer gar keine Wärmepumpe und auch kein E-Auto hat, somit den Power-Splitter nicht verwendet. Es ist klar, dass der Netzbezug ausschließlich für den Hausverbrauch erfolgt. Das Diagramm sollte dies darstellen, also auch hier gestapelte Balken anzeigen.

**Comment by ledermann** [comment]
Dies ist nun implementiert, die Änderung wird in das nächste Update `(v0.18)` mit einfließen.

Zu sehen bereits jetzt in `develop` sowie im [aktuellen Betatest](https://github.com/orgs/solectrus/discussions/3587) `pr-3533`.

**Comment by Zeppelin-PV** [comment]
DANKE !!!
![grafik](https://github.com/user-attachments/assets/bd2a42c4-d6b3-4e45-8faf-abdb22def5a6)

**Comment by Zeppelin-PV** [comment]
... folgendes festgestellt:
Instanz1 - alle images auf develop - Splitanzeige aktiv (s.o.)
Instanz2 - dashboard image auf pr-3533 - andere images auf develop - keine Splitanzeige (auch nach manuellem pull & up -d)
![grafik](https://github.com/user-attachments/assets/b4fbfb88-1dae-4255-94f1-d6cd2d125402)

**Comment by ledermann** [comment]
@Zeppelin-PV Warum das mit `pr-3533` bei dir nicht funktioniert, ist mir gerade nicht klar. Ist die Konfiguration anders? Mach mal bitte das hier auf deiner zweiten Instanz, um die relevanten Umgebungsvariablen des Dashboards zu ermitteln:

```
docker compose exec dashboard env | grep INFLUX_
```

Die Splitanzeige erscheint nur dann, wenn entweder der PowerSplitter vorhanden ist **ODER** das Haus der einzige Verbraucher ist. Letztes heißt, dass die folgenden Variablen existieren und **leer** sein müssen:

- `INFLUX_SENSOR_HEATPUMP_POWER`
- `INFLUX_SENSOR_WALLBOX_POWER`
- `INFLUX_EXCLUDE_FROM_HOUSE_POWER`

Falls eine davon nicht vorhanden oder nicht leer ist, setze sie bitte explizit auf leer, es müssen also diese Zeilen in der `.env` stehen:

```yaml
INFLUX_SENSOR_WALLBOX_POWER=
INFLUX_SENSOR_HEATPUMP_POWER=
INFLUX_EXCLUDE_FROM_HOUSE_POWER=
```

Meine Vermutung ist, dass in deiner Instanz die Variable für die Wallbox fehlt und vom Dashboard daher auf einen Standardwert gesetzt wird. Das wäre dann etwas, das ich im Konfigurator noch verbessern müsste.

**Comment by Zeppelin-PV** [comment]
Punktlandung - ja die sind auskommentiert, weil dies ja meine erste, über den Konfigurator erstellte, Instanz ist.
korrigiert - und läuft
DANKE !!!

INFLUX_SENSOR_INVERTER_POWER=SENEC:inverter_power
INFLUX_SENSOR_HOUSE_POWER=SENEC:house_power
INFLUX_SENSOR_GRID_IMPORT_POWER=SENEC:grid_power_plus
INFLUX_SENSOR_GRID_EXPORT_POWER=SENEC:grid_power_minus
INFLUX_SENSOR_BATTERY_CHARGING_POWER=SENEC:bat_power_plus
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=SENEC:bat_power_minus
INFLUX_SENSOR_BATTERY_SOC=SENEC:bat_fuel_charge
# INFLUX_SENSOR_WALLBOX_POWER=
# INFLUX_SENSOR_WALLBOX_CAR_CONNECTED=
INFLUX_SENSOR_CASE_TEMP=SENEC:case_temp
INFLUX_SENSOR_SYSTEM_STATUS=SENEC:current_state
INFLUX_SENSOR_SYSTEM_STATUS_OK=SENEC:current_state_ok
INFLUX_SENSOR_GRID_EXPORT_LIMIT=SENEC:power_ratio
INFLUX_SENSOR_INVERTER_POWER_FORECAST=forecast:watt
# INFLUX_SENSOR_HEATPUMP_POWER=
# INFLUX_SENSOR_CAR_BATTERY_SOC=

**Comment by ledermann** [comment]
Ok, prima. Den Konfigurator habe ich gerade noch verbessert, sodass es nicht mehr zu den fälschlicherweise auskommentierten Zeilen in `.env` kommt.
