### ISSUE TITLE
konfuse Anzeige "verbunden" bei Hausverbrauch in Beta pr-3747

### ISSUE THREAD

**Issue by Zeppelin-PV** [solectrus/solectrus#3751]
### Beschreibung (auf Deutsch oder Englisch)

neben dem Fehler 500 ist mir noch aufgefallen, dass im Hauptmenü "keine Verbindung" angezeigt wird, währen im neuen Menü 
gesplittete Verbraucher "verbunden" erscheint

![Screenshot 2024-12-06 224505](https://github.com/user-attachments/assets/fdd890b0-ab28-46a3-9278-cb4c83c5ff54)
![Screenshot 2024-12-06 224449](https://github.com/user-attachments/assets/efccf8b7-37a6-414e-9624-0cc472068a82)

### Welche Version von SOLECTRUS verwendest du?

Beta pr-3747

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Pi 4

### Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)

```text
gepostet in #3749
```

### Dein vollständiges `docker-compose.yml` oder `compose.yml`

```yaml
gepostet in #3749
```

### Dein vollständiges `.env`

```text
gepostet in #3749
```

**Comment by Zeppelin-PV** [comment]
keine Verbindung ist korrekt, da der SENEC unter seiner IP gerade nicht erreichbar ist, demnach ist "verbunden" nicht korrekt

**Comment by ledermann** [comment]
Danke für den Hinweis, das Problem ist jetzt behoben in `custom-consumers-64`
