### ISSUE TITLE
EV wird immer als "verbunden" angezeigt

### ISSUE THREAD

**Issue by gereons** [solectrus/solectrus#3754]
Mit PR #3747 wird mir mein Auto immer als "verbunden" angezeigt, obwohl in der InfluxDB korrekt "ev_connected: false" ankommt.

**Comment by StevieC121176** [comment]
Also mit dem neuesten Update von #3747 funktioniert es bei mir.

**Comment by ledermann** [comment]
Ja, danke für den Hinweis, das ist mit `custom-consumers-74` behoben.
