### ISSUE TITLE
Gehäuse Temperatur wird nicht mehr angezeigt (#3747)

### ISSUE THREAD

**Issue by unclej84** [solectrus/solectrus#3756]
### Beschreibung (auf Deutsch oder Englisch)

Auf der "Aktuell"-Ansicht fehlt über dem Ladestand die Temperatur des SENEC Gehäuses - im Diagramm wird eine korrekte Temperatur angezeigt

### Welche Version von SOLECTRUS verwendest du?

custom-consumers-74-g98787099

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Docker

### Gibt es sonst noch etwas?

![image](https://github.com/user-attachments/assets/3e3ffa01-323a-4cd5-a806-22d1abc0074d)

**Comment by unclej84** [comment]
Related to #3747

**Comment by unclej84** [comment]
Ich habe auch die Vermutung, dass der Ladestand nicht korrekt angezeigt werden könnte (bleibt auf 0%) - kann ich aber gerade nicht testen aufgrund fehlender Sonne (fiel mir gestern auf als ich das Image schon einmal getestet hatte - war deshalb temporär auf 3727 gewechselt)

**Comment by ledermann** [comment]
Sorry, einige Sensoren fehlten in der Strombilanz, das ist mittlerweile aber korrigiert (in `custom-consumers-75`). Der Ladestand ist meines Erachtens aber korrekt - momentan auch bei mir 0% und keine Sonne.

**Comment by gereons** [comment]
@unclej84 Ladestand konnte ich heute morgen dank Notladung beobachten - der funktioniert 👍
