### ISSUE TITLE
Mobilansicht von PR #3747 - Mouseovers ausserhalb des Bildschirms

### ISSUE THREAD

**Issue by gereons** [solectrus/solectrus#3758]
Beim Hausverbrauch werden in der Mobilansicht die Mouseovers ausserhalb des Bildschirms gezeichnet - das passiert bei denen in der Strombilanz nicht (siehe Screenshot).

Ausserdem ist mir bei der Gelegenheit aufgefallen dass der Navigationspfeil oben rechts nicht das richtige Padding zum Bildschirmrand hat.

![solectrus](https://github.com/user-attachments/assets/dd45321c-2146-493a-8ac3-83f7248e665f)

**Comment by ledermann** [comment]
Tooltips sind behoben, siehe `custom-consumers-83`. 

Eine falsche Positionierung des Navigationspfeiles kann ich aber nicht reproduzieren. Ich habe verschiedene Bildschirmgrößen ausgetestet. Wenn, dann müsste das auch ein generelles Problem sein, also auch in der Strombilanz auftreten. Das sollte ggfs. separat geklärt werden.
