### ISSUE TITLE
Position des rechten Navigationspfeil auf kleinen Handies

### ISSUE THREAD

**Issue by gereons** [solectrus/solectrus#3761]
Wie in #3758 schon beschrieben ist der rechte Navigationspfeil bei Tag/Monat/Jahr bei kleineren Handys entweder nicht mehr symmetrisch zum linken oder sogar angeschitten bis komplett unsichtbar. Bei mir tritt das bei einem iPhone 13 auf (390px Bildschirmbreite), bei einem iPhone 11 mit 375px sähe es so aus: 

![Bildschirmfoto 2024-12-09 um 15 30 08](https://github.com/user-attachments/assets/2729f2e5-9da9-4634-b9eb-6baccbd5e56e)

(simuliert mit den Firefox-Devtools)

Wenn ich das richtig sehe hat der mittlere `div` in dieser Zeile die CSS-Klasse `w-72` die ihm eine zu große Minimalgröße gibt, IMHO kann dieses `w-72` ersatzlos weg.

**Comment by ledermann** [comment]
Sehr gut, besten Dank dafür! Das `w-72` sorgt auf größeren Screens dafür, dass die Zeitraum-Navigation beim Blättern nicht hin und her springt, auf sehr kleinen Screens ist sie allerdings zu breit (und auch unnötig). Ich hatte SOLECTRUS schon länger nicht mehr auf so kleinen Geräten getestet. 

Die Korrektur ist jetzt erfolgt (in `develop` und `custom-consumers`), das `w-72` wird jetzt nur noch auf größeren Screens verwendet.
