### ISSUE TITLE
Verbrauchsaufteilung wird nicht angezeigt, wenn Hausverbrauch kleiner ist

### ISSUE THREAD

**Issue by patricknitsch** [solectrus/solectrus#3768]
### Beschreibung (auf Deutsch oder Englisch)

In der neuen Beta-Version habe ich viele Verbraucher die hohe Leistungen ziehen. Diese lasse ich aus dem Verbrauch herausrechnen, um zu sehen, was am Ende noch anderweitig verbraucht wird.
Die Ansicht funktioniert dann aber nicht, da die anderen Verbräuche höher sind, als der Hausverbrauch

<img width="674" alt="image" src="https://github.com/user-attachments/assets/7f83b59f-daa1-4299-bb95-8678da491377" />

<img width="641" alt="image" src="https://github.com/user-attachments/assets/fa2bdbda-69d1-4943-9a13-730c6fcc84d2" />

### Welche Version von SOLECTRUS verwendest du?

custom-consumers-96

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Proxmox

**Comment by ledermann** [comment]
Ich habe in diesem Zusammenhang einen Fehler korrigiert, der zu einer falschen Berechnung der Summe von "Andere" geführt hat und dann Folgefehler nach sich zog. Zu sehen in `custom-consumers-100` (bitte updaten).

Ich bin mir jedoch nicht sicher, ob das auch das von dir beschriebene Problem löst. Insbesondere irritiert mich, dass in deinen Screenshots das Ausrufezeichen-Icon zu sehen ist. Dies weist auf ein Problem hin, das **außerhalb** von SOLECTRUS liegt. Je nach Setup ist es denkbar, dass der gemeldete Hausverbrauch **kleiner** ist als die Summe der einzeln gemessenen Verbraucher. 

Dies ist beispielsweise bei meinem SENEC-Speicher der Fall, wenn die Wallbox in Benutzung ist. Während dieser Zeit meldet der SENEC-Speicher oftmals einen falschen Hausverbrauch von 0, die (unabhängig davon gemessenen) Einzelverbraucher melden aber weiter einen positiven (korrekten) Wert - es stimmen dann einige Berechnungen nicht und SOLECTRUS signalisiert das über dieses Icon. Einen Korrekturversuch unternimmt SOLECTRUS **nicht**.

Falls das Problem bei dir auch nach einem Update weiterhin auftritt, müssen wir das genauer untersuchen. Zunächst solltest du prüfen, ob es einen Grund außerhalb von SOLECTRUS gibt, der zu einem zu geringen (und somit falschen) Hausverbrauch führt.

**Comment by patricknitsch** [comment]
Jetzt ist das Ausrufezeichen weg und er zeigt Andere an. Die anderen aktiven Verbraucher werden aber nicht angezeigt. Liegt das daran, dass diese aus dem Hausverbrauch herausgerechnet sind?

![image](https://github.com/user-attachments/assets/97d2db6a-ca2a-422e-aa66-afde68f08521)

**Comment by ledermann** [comment]
Das sieht nun korrekt aus. Ja, wenn ein Verbraucher aus dem Hausverbrauch herausgerechnet werden soll, ist er nicht mehr in dieser Darstellung enthalten. Meiner Ansicht sinnvoll, denn es wird hier ja der Hausverbrauch angezeigt.

Wenn du keine weitere (Klein-)Verbraucher hast, bringt diese Darstellung natürlich keinen Mehrwert für dich, aber du hast dafür die selbstdefinierten (Groß-)Verbraucher direkt in der Strombilanz.

**Comment by patricknitsch** [comment]
Das passt für mich. Kann dann hier geschlossen werden.
