### ISSUE TITLE
Einsparung berücksichtigt EXCLUDED Verbraucher nicht bei Vergleichspreis

### ISSUE THREAD

**Issue by unclej84** [solectrus/solectrus#3786]
### Beschreibung (auf Deutsch oder Englisch)

Bei der Berechnung der Einsparung werden die Verbraucher aus `INFLUX_EXCLUDE_FROM_HOUSE_POWER` nicht berücksichtigt (Custom_Power wird nicht berücksichtigt, E-Auto wird berücksichtigt, Wärmepumpe kann ich nicht prüfen). Die Einsparung bezieht sich dann nur auf den verbleibenden Hausverbrauch. Die Oppotunitätskosten sind aktiviert, aber sollten keinen Einfluss haben.

Hier ein Beispiel:

- Netzbezug: 14,069kWh
- Hausverbrauch (ohne Custom): 13,253kWh
- Custom_Power_01: 0,79kWh
- Custom_Power_08: 0,394kWh
- Strompreis: 0,3538€/kWh
- Einspeisevergütung: 0,07€/kWh
- Netzbezugskosten: 4,97€
- Vergleichspreis erwartet: 5,11€ (Hausverbrauch + Custom)
- Vergleichspreis angezeigt: 4,69€ (nur Hausverbrauch ohne Custom)

<img width="560" alt="image" src="https://github.com/user-attachments/assets/5fdc583d-77ad-405a-bb96-4e523ab5954c" />
<img width="550" alt="image" src="https://github.com/user-attachments/assets/48fb80cb-e893-4ef3-b6f7-465954264b88" />

### Welche Version von SOLECTRUS verwendest du?

custom-consumers-128-g629ec8c3

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Docker

**Comment by ledermann** [comment]
Danke für die präzise Beschreibung und dass du mich auf einen Bereich hinweist, der dringend eines Refactorings bedarf. Ich habe das korrigiert, werde das demnächst aber noch gründlicher angehen.
