### ISSUE TITLE
Neuer Speicher Zustand wird nur als Nummer angezeigt

### ISSUE THREAD

**Issue by patricknitsch** [solectrus/solectrus#3802]
### Beschreibung (auf Deutsch oder Englisch)

Seit Einführung der Aufwachladung gibt es Nummer 99. Diese wird aktuell nur als 99 angezeigt

![image](https://github.com/user-attachments/assets/2a0d1955-6f30-4815-be6c-86a574ced2b1)

### Welche Version von SOLECTRUS verwendest du?

custom-consumers-145

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Proxmox LXC

**Comment by ledermann** [comment]
Einfache Lösung: SENEC-Collector aktualisieren (falls nicht bereits aktuell) und ganz wichtig: Neu starten. Die Status-Bezeichnungen werden nur einmal beim Start vom SENEC-Speicher abgerufen.

Also:

```
docker compose down
docker compose pull
docker compose up -d
```

**Comment by patricknitsch** [comment]
Auf latest stand er schon. Der Neustart hat aber geholfen. Danke!
