### ISSUE TITLE
Inkonsistente Beschriftung

### ISSUE THREAD

**Issue by unclej84** [solectrus/solectrus#3832]
### Beschreibung (auf Deutsch oder Englisch)

Die neuen Labels im Top-Menü zeigen "Hausverbrauch" und der Sensor/Balken/Diagramm  zeigen "Haus-Verbrauch" - wäre es nicht besser dies einheitlich zu haben?

### Welche Version von SOLECTRUS verwendest du?

custom-consumers-208-g984228bd

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Docker

### Gibt es sonst noch etwas?

<img width="1109" alt="image" src="https://github.com/user-attachments/assets/270317ce-72a6-4fed-ba0b-c8e71af6e1ea" />

**Comment by unclej84** [comment]
Thanks 😃

**Comment by ledermann** [comment]
Danke für den Bugreport. Der "Hausverbrauch" wird nun einheitlich verwendet - nur wenn der Platz zu eng wird, erfolgt eine Silbentrennung.
