### ISSUE TITLE
arm64 build

### ISSUE THREAD

**Issue by daschx** [solectrus/solectrus#926]
Hallo,
Ich versuche alles auf einem NanoPi M4 zum laufen zu bringen. Er hat einen arm64 Prozessor, so das influxdb darauf läuft.
Aber beim starten von solectrus kommt immer 
`app_1 | standard_init_linux.go:228: exec user process caused: exec format error`

Ist es möglich solectrus auf einem arm64 Prozessor zum laufen zu bringen?

Beim builden auf dem nanopi bin ich irgendwie an den zwei rails images verzweifelt.

**Comment by ledermann** [comment]
Seit Version [v0.5.8](https://github.com/solectrus/solectrus/releases/tag/v0.5.8) gibt es das Docker image auch für `linux/arm64`.

**Comment by ledermann** [comment]
Es funktioniert weiterhin nicht. Fehlermeldung auf einem Pi4 mit 64bit Raspberry Pi OS (Debian 11) beim Start des Containers:

```
exec docker/startup.sh: exec format error
```

**Comment by ledermann** [comment]
Mit Version [v0.7.5](/solectrus/solectrus/releases/tag/v0.7.5) funktioniert das Docker Image nun auch wirklich auf einem Raspi 64bit :)
